using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Model.FluentMock;
using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Fixtures.Models;

internal static class WithDifferentPrimaryKeys
{
  public class SimpleEntity
  {
    public int Id { get; set; }
    public string? Name { get; set; }
  }

  public class CompositeEntity
  {
    public Guid Id1 { get; set; }
    public int Id2 { get; set; }
    public string? Name { get; set; }
  }

  public static IEntityModel CreateSimpleEntityModel(bool autoGeneratedId)
  {
    EntityTypeDelegator entityType = new EntityTypeDelegator(typeof(SimpleEntity), autoGeneratedId);

    IPrimaryKeyPropertyModel idProperty = PrimaryKeyPropertyModelBuilder.Build(_ => _
      .SetName(nameof(SimpleEntity.Id))
      .SetType(typeof(int))
      .SetIndex(0)
      .SetIsAutoGenerated(autoGeneratedId)
      .SetHasMember(true)
      .SetProperty(typeof(SimpleEntity).GetRequiredProperty(nameof(SimpleEntity.Id), BindingFlags.Instance | BindingFlags.Public)));

    IPropertyModel nameProperty = PropertyModelBuilder.Build(_ => _
      .SetName(nameof(SimpleEntity.Name))
      .SetType(typeof(string))
      .SetIndex(1)
      .SetHasMember(true)
      .SetProperty(typeof(SimpleEntity).GetRequiredProperty(nameof(SimpleEntity.Name), BindingFlags.Instance | BindingFlags.Public)));

    return EntityModelBuilder.Build(_ => _
      .SetType(entityType)
      .SetName(nameof(SimpleEntity))
      .SetProperties(idProperty, nameProperty)
      .SetPrimaryKey(_ => _
        .SetIsComposite(false)
        .SetAutoGeneratedProperty(idProperty)
        .SetType(typeof(int))
        .SetProperties(idProperty))
      .SetNavigations());
  }

  public static IEntityModel CreateCompositeEntityModel(bool autoGeneratedId)
  {
    EntityTypeDelegator entityType = new EntityTypeDelegator(typeof(CompositeEntity), autoGeneratedId);

    IPrimaryKeyPropertyModel id1Property = PrimaryKeyPropertyModelBuilder.Build(_ => _
      .SetName(nameof(CompositeEntity.Id1))
      .SetType(typeof(Guid))
      .SetIndex(0)
      .SetIsAutoGenerated(false)
      .SetHasMember(true)
      .SetProperty(typeof(CompositeEntity).GetRequiredProperty(nameof(CompositeEntity.Id1), BindingFlags.Instance | BindingFlags.Public)));

    IPrimaryKeyPropertyModel id2Property = PrimaryKeyPropertyModelBuilder.Build(_ => _
      .SetName(nameof(CompositeEntity.Id2))
      .SetType(typeof(int))
      .SetIndex(1)
      .SetIsAutoGenerated(autoGeneratedId)
      .SetHasMember(true)
      .SetProperty(typeof(CompositeEntity).GetRequiredProperty(nameof(CompositeEntity.Id2), BindingFlags.Instance | BindingFlags.Public)));

    IPropertyModel nameProperty = PropertyModelBuilder.Build(_ => _
      .SetName(nameof(SimpleEntity.Name))
      .SetType(typeof(string))
      .SetIndex(2)
      .SetHasMember(true)
      .SetProperty(typeof(SimpleEntity).GetRequiredProperty(nameof(SimpleEntity.Name), BindingFlags.Instance | BindingFlags.Public)));

    return EntityModelBuilder.Build(_ => _
      .SetType(entityType)
      .SetName(nameof(SimpleEntity))
      .SetProperties(id1Property, id2Property, nameProperty)
      .SetPrimaryKey(_ => _
        .SetIsComposite(true)
        .SetAutoGeneratedProperty(id2Property)
        .SetType(typeof((Guid, int)))
        .SetProperties(id1Property, id2Property))
      .SetNavigations());
  }

  private class EntityTypeDelegator : TypeDelegator
  {
    private readonly bool _autoGeneratedId;

    public EntityTypeDelegator(Type entityType, bool autoGeneratedId)
      : base(entityType)
    {
      _autoGeneratedId = autoGeneratedId;
    }

    public override string Name => _autoGeneratedId ? $"{base.Name}AutoGen" : base.Name;

    public override string? FullName => _autoGeneratedId ? $"{base.FullName}AutoGen" : base.FullName;
  }
}
