using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Model.FluentMock;
using System.Collections;
using System.Data.Common;
using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Fixtures.Models;

internal static class WithNavigationOnParent
{
  public class Parent
  {
    public Guid Id { get; set; } // 0
    public string? Name { get; set; } // 1

    public ChildA? ChildA { get; set; }
    public IList<ChildB>? ChildrenB { get; set; }
  }

  public class ChildA
  {
    public Guid Id { get; set; } // 2
    public string? Name { get; set; } // 3
    public Guid ParentId { get; set; } // 4
  }

  public class ChildB
  {
    public int Id { get; set; } // 5
    public string? Name { get; set; } // 6
    public Guid ParentId { get; set; } // 7
  }

  public static readonly IEntityModel ParentModel = CreateParentModel();
  public static readonly IEntityModel ChildAModel = CreateChildAModel();
  public static readonly IEntityModel ChildBModel = CreateChildBModel();

  private static IEntityModel CreateParentModel()
  {
    IPrimaryKeyPropertyModel idProperty = PrimaryKeyPropertyModelBuilder.Build(_ => _
      .SetName("Id")
      .SetIndex(0)
      .SetType(typeof(Guid))
      .SetIsAutoGenerated(false)
      .SetMemberAccess(MemberAccess.Property)
      .SetProperty(typeof(Parent).GetRequiredProperty(nameof(Parent.Id), BindingFlags.Instance | BindingFlags.Public)));

    IPropertyModel nameProperty = PropertyModelBuilder.Build(_ => _
      .SetName("Name")
      .SetIndex(1)
      .SetType(typeof(string))
      .SetMemberAccess(MemberAccess.Property)
      .SetProperty(typeof(Parent).GetRequiredProperty(nameof(Parent.Name), BindingFlags.Instance | BindingFlags.Public)));

    INavigationModel childANavigation = SimpleNavigationModelBuilder.Build(_ => _
      .SetId(1)
      .SetIndex(0)
      .SetName(nameof(Parent.ChildA))
      .SetType(typeof(ChildA))
      .SetIsOnDependent(true)
      .SetIsCollection(false)
      .SetMemberAccess(MemberAccess.Property)
      .SetProperty(typeof(Parent).GetRequiredProperty(nameof(Parent.ChildA), BindingFlags.Instance | BindingFlags.Public))
      .SetTo(_ => _
        .SetType(typeof(ChildA))
        .SetPrimaryKey(_ => _
          .SetType(typeof(Guid)))));

    INavigationModel childrenBNavigation = SimpleNavigationModelBuilder.Build(_ => _
      .SetId(2)
      .SetIndex(1)
      .SetName(nameof(Parent.ChildrenB))
      .SetType(typeof(ICollection<ChildB>))
      .SetIsOnDependent(true)
      .SetIsCollection(true)
      .SetMemberAccess(MemberAccess.Property)
      .SetProperty(typeof(Parent).GetRequiredProperty(nameof(Parent.ChildrenB), BindingFlags.Instance | BindingFlags.Public))
      .SetTo(_ => _
        .SetType(typeof(ChildB))
        .SetPrimaryKey(_ => _
          .SetType(typeof(int)))));

    return EntityModelBuilder.Build(_ => _
      .SetType(typeof(Parent))
      .SetName("Parent")
      .SetPrimaryKey(_ => _
        .SetIsComposite(false)
        .SetAutoGeneratedProperty(null as IPrimaryKeyPropertyModel)
        .SetType(typeof(Guid))
        .SetProperties(idProperty))
      .SetProperties(idProperty, nameProperty)
      .SetInitializer(_ => _
        .SetConstructor(typeof(Parent).GetRequiredConstructor())
        .SetConstructorProperties()
        .SetInitializerProperties(idProperty, nameProperty))
      .SetNavigations(childANavigation, childrenBNavigation));
  }

  private static IEntityModel CreateChildAModel()
  {
    IPrimaryKeyPropertyModel idProperty = PrimaryKeyPropertyModelBuilder.Build(_ => _
      .SetName("Id")
      .SetIndex(0)
      .SetType(typeof(Guid))
      .SetIsAutoGenerated(false)
      .SetMemberAccess(MemberAccess.Property)
      .SetProperty(typeof(ChildA).GetRequiredProperty(nameof(ChildA.Id), BindingFlags.Instance | BindingFlags.Public)));

    IPropertyModel nameProperty = PropertyModelBuilder.Build(_ => _
      .SetName("Name")
      .SetIndex(1)
      .SetType(typeof(string))
      .SetMemberAccess(MemberAccess.Property)
      .SetProperty(typeof(ChildA).GetRequiredProperty(nameof(ChildA.Name), BindingFlags.Instance | BindingFlags.Public)));

    INavigationModel parentNavigation = SimpleNavigationModelBuilder.Build(_ => _
      .SetId(1)
      .SetType(typeof(Parent))
      .SetIsOnDependent(false)
      .SetIsCollection(false)
      .SetMemberAccess(MemberAccess.None)
      .SetProperty(null!)
      .SetTo(_ => _
        .SetType(typeof(Parent))
        .SetPrimaryKey(_ => _
          .SetType(typeof(Guid)))));

    IPropertyModel parentIdProperty = PropertyModelBuilder.Build(_ => _
      .SetName("ParentId")
      .SetIndex(2)
      // .SetKeyIndex(0)
      .SetType(typeof(Guid))
      .SetMemberAccess(MemberAccess.Property)
      .SetProperty(typeof(ChildA).GetRequiredProperty(nameof(ChildA.ParentId), BindingFlags.Instance | BindingFlags.Public))
      /*.SetNavigation(parentNavigation)*/);

    return EntityModelBuilder.Build(_ => _
      .SetType(typeof(ChildA))
      .SetName("ChildA")
      .SetPrimaryKey(_ => _
        .SetIsComposite(false)
        .SetAutoGeneratedProperty(null as IPrimaryKeyPropertyModel)
        .SetType(typeof(Guid))
        .SetProperties(idProperty))
      .SetProperties(idProperty, nameProperty, parentIdProperty)
      .SetInitializer(_ => _
        .SetConstructor(typeof(ChildA).GetRequiredConstructor())
        .SetConstructorProperties()
        .SetInitializerProperties(idProperty, nameProperty, parentIdProperty))
      .SetNavigations(parentNavigation));
  }

  public static IEntityModel CreateChildBModel()
  {
    IPrimaryKeyPropertyModel idProperty = PrimaryKeyPropertyModelBuilder.Build(_ => _
      .SetName("Id")
      .SetIndex(0)
      .SetType(typeof(int))
      .SetIsAutoGenerated(true)
      .SetMemberAccess(MemberAccess.Property)
      .SetProperty(typeof(ChildB).GetRequiredProperty(nameof(ChildB.Id), BindingFlags.Instance | BindingFlags.Public)));

    IPropertyModel nameProperty = PropertyModelBuilder.Build(_ => _
      .SetName("Name")
      .SetIndex(1)
      .SetType(typeof(string))
      .SetMemberAccess(MemberAccess.Property)
      .SetProperty(typeof(ChildB).GetRequiredProperty(nameof(ChildB.Name), BindingFlags.Instance | BindingFlags.Public)));

    INavigationModel parentNavigation = SimpleNavigationModelBuilder.Build(_ => _
      .SetId(2)
      .SetType(typeof(Parent))
      .SetIsOnDependent(false)
      .SetIsCollection(true)
      .SetMemberAccess(MemberAccess.None)
      .SetProperty(null)
      .SetTo(_ => _
        .SetType(typeof(Parent))
        .SetPrimaryKey(_ => _
          .SetType(typeof(Guid)))));

    IPropertyModel parentIdProperty = PropertyModelBuilder.Build(_ => _
      .SetName("ParentId")
      .SetIndex(2)
      // .SetKeyIndex(0)
      .SetType(typeof(Guid))
      .SetMemberAccess(MemberAccess.Property)
      .SetProperty(typeof(ChildB).GetRequiredProperty(nameof(ChildB.ParentId), BindingFlags.Instance | BindingFlags.Public))
      /*.SetNavigation(parentNavigation)*/);

    return EntityModelBuilder.Build(_ => _
      .SetType(typeof(ChildB))
      .SetName("ChildB")
      .SetPrimaryKey(_ => _
        .SetIsComposite(false)
        .SetAutoGeneratedProperty(null as IPrimaryKeyPropertyModel)
        .SetType(typeof(int))
        .SetProperties(idProperty))
      .SetProperties(idProperty, nameProperty, parentIdProperty)
      .SetInitializer(_ => _
        .SetConstructor(typeof(ChildB).GetRequiredConstructor())
        .SetConstructorProperties()
        .SetInitializerProperties(idProperty, nameProperty, parentIdProperty))
      .SetNavigations(parentNavigation));
  }

  public class ChildBEqualityComparer : IEqualityComparer<ChildB>
  {
    bool IEqualityComparer<ChildB>.Equals(ChildB? x, ChildB? y)
    {
      if (x is null)
        return y is null;

      if (y is null)
        return false;

      return x.Id == y.Id;
    }

    int IEqualityComparer<ChildB>.GetHashCode(ChildB obj)
    {
      return obj.Id.GetHashCode();
    }
  }

  public record FakeDbDataRow(Parent Parent, ChildA? ChildA, ChildB? ChildB);

  public class FakeDbDataReader : DbDataReader
  {
    private readonly IEnumerator<FakeDbDataRow> _enumerator;

    public FakeDbDataReader(IEnumerable<FakeDbDataRow> enumerable)
    {
      _enumerator = enumerable.GetEnumerator();
    }

    private static Exception NullValueException => new InvalidOperationException("Value was null.");

    private static Exception InvalidOrdinal => new ArgumentException("Invalid ordinal.");

    private Parent Parent => _enumerator.Current.Parent;
    private ChildA ChildA => _enumerator.Current.ChildA ?? throw InvalidOrdinal;
    private ChildB ChildB => _enumerator.Current.ChildB ?? throw InvalidOrdinal;

    public override Guid GetGuid(int ordinal)
    {
      if (_enumerator.Current.ChildA is null)
      {
        return ordinal switch
        {
          0 => Parent.Id,
          4 => ChildB.ParentId,
          _ => throw new ArgumentException("Invalid ordinal.", nameof(ordinal))
        };
      }
      else
      {
        return ordinal switch
        {
          0 => Parent.Id,
          2 => ChildA.Id,
          4 => ChildA.ParentId,
          7 => ChildB.ParentId,
          _ => throw new ArgumentException("Invalid ordinal.", nameof(ordinal))
        };
      }
    }

    public override int GetInt32(int ordinal)
    {
      if (_enumerator.Current.ChildA is null)
      {
        return ordinal switch
        {
          2 => ChildB.Id,
          _ => throw new ArgumentException("Invalid ordinal.", nameof(ordinal))
        };
      }
      else
      {
        return ordinal switch
        {
          7 => ChildB.Id,
          _ => throw new ArgumentException("Invalid ordinal.", nameof(ordinal))
        };
      }
    }

    public override string GetString(int ordinal)
    {
      if (_enumerator.Current.ChildA is null)
      {
        return ordinal switch
        {
          1 => Parent.Name ?? throw NullValueException,
          3 => ChildB.Name ?? throw NullValueException,
          _ => throw new ArgumentException("Invalid ordinal.", nameof(ordinal))
        };
      }
      else
      {
        return ordinal switch
        {
          1 => Parent.Name ?? throw NullValueException,
          3 => ChildA.Name ?? throw NullValueException,
          6 => ChildB.Name ?? throw NullValueException,
          _ => throw new ArgumentException("Invalid ordinal.", nameof(ordinal))
        };
      }
    }

    public override bool IsDBNull(int ordinal)
    {
      return ordinal switch
      {
        1 => Parent.Name is null,
        3 => ChildA.Name is null,
        6 => ChildA.Name is null,
        _ => false
      };
    }

    public override bool Read()
    {
      return _enumerator.MoveNext();
    }

    #region Not implemented

    public override object this[int ordinal] => throw new NotImplementedException();

    public override object this[string name] => throw new NotImplementedException();

    public override int Depth => throw new NotImplementedException();

    public override int FieldCount => throw new NotImplementedException();

    public override bool HasRows => throw new NotImplementedException();

    public override bool IsClosed => throw new NotImplementedException();

    public override int RecordsAffected => throw new NotImplementedException();

    public override bool GetBoolean(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override byte GetByte(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override long GetBytes(int ordinal, long dataOffset, byte[]? buffer, int bufferOffset, int length)
    {
      throw new NotImplementedException();
    }

    public override char GetChar(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override long GetChars(int ordinal, long dataOffset, char[]? buffer, int bufferOffset, int length)
    {
      throw new NotImplementedException();
    }

    public override string GetDataTypeName(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override DateTime GetDateTime(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override decimal GetDecimal(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override double GetDouble(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override IEnumerator GetEnumerator()
    {
      throw new NotImplementedException();
    }

    public override Type GetFieldType(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override float GetFloat(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override short GetInt16(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override long GetInt64(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override string GetName(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override int GetOrdinal(string name)
    {
      throw new NotImplementedException();
    }

    public override object GetValue(int ordinal)
    {
      throw new NotImplementedException();
    }

    public override int GetValues(object[] values)
    {
      throw new NotImplementedException();
    }

    public override bool NextResult()
    {
      throw new NotImplementedException();
    }

    #endregion
  }
}
