site_name: Code Architects Enterprise Solution Framework
site_url: https://github.com/codearchitects/CodeArchitects.EnterprisePlatform.Server
theme: readthedocs
nav:
  - Home: index.md
  - Messaging: messaging.md
  - Messaging with Dapr: messaging-dapr.md
  - State management: statemanagement.md
  - State management with Dapr: statemanagement-dapr.md