using CodeArchitects.Platform.Data.AdoNet.Interceptors;
using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Visitors;
using System.Data.Common;

namespace CodeArchitects.Platform.Data.AdoNet.Executor;

internal partial class Executor<TDbCommand>
{
  public void ExecuteInsertMany<TEntity, TKey>(TDbCommand command, IEnumerable<TEntity> entities, IEntityModel<TEntity, TKey> model)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    ExecuteInsertMany(command, entities, model, default);

    ExecuteInsertManyGraphVisitor visitor = new(this, command);
    foreach (TEntity entity in entities)
    {
      Graph.Visit(entity, model, visitor);
    }
  }

  public async Task ExecuteInsertManyAsync<TEntity, TKey>(TDbCommand command, IEnumerable<TEntity> entities, IEntityModel<TEntity, TKey> model, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    await ExecuteInsertManyAsync(command, entities, model, default, cancellationToken);

    ExecuteInsertManyGraphVisitor visitor = new(this, command);
    foreach (TEntity entity in entities)
    {
      await Graph.VisitAsync(entity, model, visitor, cancellationToken);
    }
  }

  private void ExecuteInsertMany(TDbCommand command, IEnumerable<object> nodes, IEntityModel model, NavigationContext context)
  {
    BuildInsertManyCommand(command, nodes, model, context);
    using DbDataReader? reader = command.ExecuteReader();
    TrySetAutoGeneratedColumn(nodes, model, reader);
  }

  private async Task ExecuteInsertManyAsync(TDbCommand command, IEnumerable<object> nodes, IEntityModel model, NavigationContext context, CancellationToken cancellationToken)
  {
    BuildInsertManyCommand(command, nodes, model, context);
    await using DbDataReader? reader = await command.ExecuteReaderAsync(cancellationToken);
    await TrySetAutoGeneratedColumnAsync(nodes, model, reader, cancellationToken);
  }

  private static void TrySetAutoGeneratedColumn(IEnumerable<object> nodes, IEntityModel model, DbDataReader reader)
  {
    if (model.AutoGeneratedColumn is not IAccessibleColumnModel autoGeneratedColumn)
      return;

    foreach (object node in nodes)
    {
      _ = reader.Read();
      object? result = reader.GetValue(0);
      if (result is null)
        continue;

      autoGeneratedColumn.SetValue(node, result);
    }
  }

  private static async Task TrySetAutoGeneratedColumnAsync(IEnumerable<object> nodes, IEntityModel model, DbDataReader reader, CancellationToken cancellationToken)
  {
    if (model.AutoGeneratedColumn is not IAccessibleColumnModel autoGeneratedColumn)
      return;

    foreach (object node in nodes)
    {
      _ = await reader.ReadAsync(cancellationToken);
      object? result = reader.GetValue(0);
      if (result is null)
        continue;

      autoGeneratedColumn.SetValue(node, result);
    }
  }

  private void BuildInsertManyCommand(TDbCommand command, IEnumerable<object> nodes, IEntityModel model, NavigationContext context)
  {
    _commandBuilder.BuildInsertManyCommand(command, nodes, model, context);
    _interceptor.OnCommandBuilt(OperationType.InsertMany, command);
  }

  private sealed class ExecuteInsertManyGraphVisitor : ExecuteInsertGraphVisitor
  {
    public ExecuteInsertManyGraphVisitor(Executor<TDbCommand> executor, TDbCommand command)
      : base(executor, command)
    {
    }

    public override bool VisitRoot(object root, IEntityModel model)
    {
      return true;
    }

    public override Task<bool> VisitRootAsync(object root, IEntityModel model, CancellationToken cancellationToken = default)
    {
      return Task.FromResult(true);
    }
  }
}
