using CodeArchitects.Platform.Data.AdoNet.Interceptors;
using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Visitors;
using CodeArchitects.Platform.Data.Features.Associations;
using System.Diagnostics;

namespace CodeArchitects.Platform.Data.AdoNet.Executor;

internal partial class Executor<TDbCommand>
{
  public void ExecuteInsert<TEntity, TKey>(TDbCommand command, TEntity entity, IEntityModel<TEntity, TKey> model)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    ExecuteInsertGraphVisitor visitor = new(this, command);
    Graph.Visit(entity, model, visitor);
  }

  public Task ExecuteInsertAsync<TEntity, TKey>(TDbCommand command, TEntity entity, IEntityModel<TEntity, TKey> model, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    ExecuteInsertGraphVisitor visitor = new(this, command);
    return Graph.VisitAsync(entity, model, visitor, cancellationToken);
  }

  private async Task ExecuteInsertAsync(TDbCommand command, object node, IEntityModel model, NavigationContext context, CancellationToken cancellationToken)
  {
    BuildInsertCommand(command, node, model, context);
    object? result = await command.ExecuteScalarAsync(cancellationToken);
    TrySetAutoGeneratedColumn(node, model, result);
  }

  private void ExecuteInsert(TDbCommand command, object node, IEntityModel model, NavigationContext context)
  {
    BuildInsertCommand(command, node, model, context);
    object? result = command.ExecuteScalar();
    TrySetAutoGeneratedColumn(node, model, result);
  }

  private void BuildInsertCommand(TDbCommand command, object node, IEntityModel model, NavigationContext context)
  {
    _commandBuilder.BuildInsertCommand(command, node, model, context);
    _interceptor.OnCommandBuilt(OperationType.Insert, command);
  }

  private class ExecuteInsertGraphVisitor : IGraphVisitor, IAsyncGraphVisitor
  {
    private readonly Executor<TDbCommand> _executor;
    private readonly TDbCommand _command;

    public ExecuteInsertGraphVisitor(Executor<TDbCommand> executor, TDbCommand command)
    {
      _executor = executor;
      _command = command;
    }

    public virtual bool VisitRoot(object root, IEntityModel model)
    {
      _executor.ExecuteInsert(_command, root, model, default);
      return true;
    }

    public virtual async Task<bool> VisitRootAsync(object root, IEntityModel model, CancellationToken cancellationToken = default)
    {
      await _executor.ExecuteInsertAsync(_command, root, model, default, cancellationToken);
      return true;
    }

    public bool VisitSimpleCollection(IReadOnlyCollection<object> nodes, NavigationContext<IAccessibleSimpleNavigationModel> context)
    {
      if (context.NavigationModel.IsOnDependent)
        return false;

      if (context.NavigationModel.AssociationKind is AssociationKind.IntraAggregate)
      {
        _executor.ExecuteInsertMany(_command, nodes, context.EntityModel, context);
      }

      return true;
    }

    public async Task<bool> VisitSimpleCollectionAsync(IReadOnlyCollection<object> nodes, NavigationContext<IAccessibleSimpleNavigationModel> context, CancellationToken cancellationToken = default)
    {
      if (context.NavigationModel.IsOnDependent)
        return false;

      if (context.NavigationModel.AssociationKind is AssociationKind.IntraAggregate)
      {
        await _executor.ExecuteInsertManyAsync(_command, nodes, context.EntityModel, context, cancellationToken);
      }

      return true;
    }

    public bool VisitSkipCollection(IReadOnlyCollection<object> nodes, NavigationContext<IAccessibleSkipNavigationModel> context)
    {
      IEnumerable<object> junctionEntities = CreateJunctionEntities(nodes, context);
      _executor.ExecuteInsertMany(_command, junctionEntities, context.NavigationModel.JunctionEntity, default);
      return false;
    }

    public async Task<bool> VisitSkipCollectionAsync(IReadOnlyCollection<object> nodes, NavigationContext<IAccessibleSkipNavigationModel> context, CancellationToken cancellationToken = default)
    {
      IEnumerable<object> junctionEntities = CreateJunctionEntities(nodes, context);
      await _executor.ExecuteInsertManyAsync(_command, junctionEntities, context.NavigationModel.JunctionEntity, default, cancellationToken);
      return false;
    }

    public bool VisitSimpleCollectionNode(object node, NavigationContext<IAccessibleSimpleNavigationModel> context)
    {
      if (context.NavigationModel.IsOnDependent)
      {
        Debug.Fail("Did not expect an on-dependent navigation.");
        return false;
      }

      if (context.NavigationModel.AssociationKind is AssociationKind.InterAggregate)
      {
        _executor.ExecuteUpdate(_command, node, context.NavigationModel.NavigationEntity, context);
        return false;
      }

      return true;
    }

    public async Task<bool> VisitSimpleCollectionNodeAsync(object node, NavigationContext<IAccessibleSimpleNavigationModel> context, CancellationToken cancellationToken = default)
    {
      if (context.NavigationModel.IsOnDependent)
      {
        Debug.Fail("Did not expect an on-dependent navigation.");
        return false;
      }

      if (context.NavigationModel.AssociationKind is AssociationKind.InterAggregate)
      {
        await _executor.ExecuteUpdateAsync(_command, node, context.NavigationModel.NavigationEntity, context, cancellationToken);
        return false;
      }

      return true;
    }

    public bool VisitSkipCollectionNode(object node, NavigationContext<IAccessibleSkipNavigationModel> context)
    {
      Debug.Fail("This point should be unreachable.");
      return false;
    }

    public Task<bool> VisitSkipCollectionNodeAsync(object node, NavigationContext<IAccessibleSkipNavigationModel> context, CancellationToken cancellationToken = default)
    {
      Debug.Fail("This point should be unreachable.");
      return Task.FromResult(false);
    }

    public bool VisitReferenceNode(object node, NavigationContext<IAccessibleSimpleNavigationModel> context)
    {
      if (context.NavigationModel.IsOnDependent)
        return false;

      if (context.NavigationModel.AssociationKind is AssociationKind.IntraAggregate)
      {
        _executor.ExecuteInsert(_command, node, context.EntityModel, context);
        return true;
      }
      else
      {
        _executor.ExecuteUpdate(_command, node, context.EntityModel, context);
        return false;
      }
    }

    public async Task<bool> VisitReferenceNodeAsync(object node, NavigationContext<IAccessibleSimpleNavigationModel> context, CancellationToken cancellationToken = default)
    {
      if (context.NavigationModel.IsOnDependent)
        return false;

      if (context.NavigationModel.AssociationKind is AssociationKind.IntraAggregate)
      {
        await _executor.ExecuteInsertAsync(_command, node, context.EntityModel, context, cancellationToken);
        return true;
      }
      else
      {
        await _executor.ExecuteUpdateAsync(_command, node, context.EntityModel, context, cancellationToken);
        return false;
      }
    }

    private static IEnumerable<object> CreateJunctionEntities(IReadOnlyCollection<object> nodes, NavigationContext<IAccessibleSkipNavigationModel> context)
    {
      (object parent, IAccessibleSkipNavigationModel navigationModel) = context;

      foreach (var node in nodes)
      {
        yield return navigationModel.CreateJunction(parent, node);
      }
    }
  }
}
