using CodeArchitects.Platform.Data.AdoNet.Model;

namespace CodeArchitects.Platform.Data.AdoNet.Executor;

internal partial class Executor<TDbCommand>
{
  public void ExecuteUpsert<TEntity, TKey>(TDbCommand command, TEntity entity, IEntityModel<TEntity, TKey> model)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    _commandBuilder.BuildUpsertCommand(command, entity, model);
    object? result = command.ExecuteScalar();
    TrySetAutoGeneratedColumn(entity, model, result);
  }

  public async Task ExecuteUpsertAsync<TEntity, TKey>(TDbCommand command, TEntity entity, IEntityModel<TEntity, TKey> model, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    _commandBuilder.BuildUpsertCommand(command, entity, model);
    object? result = await command.ExecuteScalarAsync(cancellationToken);
    TrySetAutoGeneratedColumn(entity, model, result);
  }
}
