using CodeArchitects.Platform.Data.AdoNet.Materialization;
using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Navigation;
using CodeArchitects.Platform.Data.AdoNet.Sql;
using CodeArchitects.Platform.Data.Tracking;
using System.Collections;
using System.Data.Common;

namespace CodeArchitects.Platform.Data.AdoNet.Executor;

internal class Executor : IExecutor
{
  private readonly ISqlTextBuilder _sqlBuilder;
  private readonly IMaterializer _materializer;
  private readonly ITrackingContext _trackingContext;

  public Executor(ISqlTextBuilder sqlBuilder, IMaterializer materializer, ITrackingContext trackingContext)
  {
    _sqlBuilder = sqlBuilder;
    _materializer = materializer;
    _trackingContext = trackingContext;
  }

  public async Task<TEntity?> ExecuteSelectCommandAsync<TEntity, TKey>(DbConnection connection, TKey key, NavigationSpec spec, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    using DbCommand command = connection.CreateCommand();

    command.CommandText = _sqlBuilder.BuildSelectText(spec);
    // Set parameters

    DbDataReader reader = await command.ExecuteReaderAsync(cancellationToken);
    object? entity = await _materializer.ReadEntityAsync(reader, spec, cancellationToken);

    return (TEntity?)entity;
  }

  public Task ExecuteInsertCommandAsync<TEntity, TKey>(DbConnection connection, TEntity entity, IEntityModel model, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    return ExecuteInsertCommandAsync(connection, entity, model, default, cancellationToken);
  }

  private async Task ExecuteInsertCommandAsync(DbConnection connection, object entity, IEntityModel model, NavigationContext navigationContext, CancellationToken cancellationToken)
  {
    using DbCommand command = connection.CreateCommand();

    // command.CommandText = _sqlBuilder.BuildInsertText(model);
    // Set parameters

    object? result = await command.ExecuteScalarAsync(cancellationToken);
    if (model.PrimaryKey.AutoGeneratedProperty is { } autoGeneratedProperty)
    {
      autoGeneratedProperty.Accessor.Set(entity, result);
    }

    int count = model.PrimaryKey.Properties.Count;
    object?[] keyValues = new object?[count];
    for (int i = 0; i < count; i++)
    {
      keyValues[i] = model.PrimaryKey.Properties[i].Accessor.Get(entity);
    }

    foreach (INavigationModel navigationModel in model.Navigations)
    {
      if (navigationModel.IsOnDependent && navigationModel.IsAggregation)
      {
        object? navigation = navigationModel.Accessor.Get(entity);
        if (navigation is null)
          continue;

        if (!navigationModel.IsCollection)
        {
          await ExecuteInsertCommandAsync(connection, navigation, navigationModel.To, new NavigationContext(navigationModel.Id, keyValues), cancellationToken);
          continue;
        }

        foreach (object element in (IEnumerable)navigation)
        {
          await ExecuteInsertCommandAsync(connection, element, navigationModel.To, new NavigationContext(navigationModel.Id, keyValues), cancellationToken);
        }
        continue;
      }

      if (navigationModel is ISkipNavigationModel skipNavigationModel)
      {
        IEnumerable? collection = (IEnumerable?)navigationModel.Accessor.Get(entity);
        if (collection is null)
          continue;

        foreach (object element in collection)
        {
          object joinEntity = skipNavigationModel.CreateJoin(entity, element);
          await ExecuteInsertCommandAsync(connection, joinEntity, skipNavigationModel.JoinEntity, default, cancellationToken);
        }
      }
    }
  }
}
