using CodeArchitects.Platform.Data.AdoNet.Interceptors;
using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Visitors;
using System.Data.Common;

namespace CodeArchitects.Platform.Data.AdoNet.Executor;

internal partial class Executor<TDbCommand>
{
  public async Task ExecuteInsertManyAsync<TEntity, TKey>(TDbCommand command, IEnumerable<TEntity> entities, IEntityModel<TEntity, TKey> model, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    await ExecuteInsertManyAsync(command, entities, model, default, cancellationToken);

    ExecuteInsertManyGraphVisitor visitor = new(this, command);
    foreach (TEntity entity in entities)
    {
      await Graph.VisitAsync(entity, model, visitor, cancellationToken);
    }
  }

  private async Task ExecuteInsertManyAsync(TDbCommand command, IEnumerable<object> nodes, IEntityModel model, NavigationContext context, CancellationToken cancellationToken)
  {
    _commandBuilder.BuildInsertManyCommand(command, nodes, model, context);
    _interceptor.OnCommandBuilt(OperationType.InsertMany, command);

    await using DbDataReader? reader = await command.ExecuteReaderAsync(cancellationToken);
    if (model.AutoGeneratedColumn is { } autoGeneratedColumn)
    {
      foreach (object node in nodes)
      {
        _ = await reader.ReadAsync(cancellationToken);
        object? result = reader.GetValue(0);
        if (result is null)
          continue;

        autoGeneratedColumn.SetValue(node, result);
      }
    }
  }

  private class ExecuteInsertManyGraphVisitor : ExecuteInsertGraphVisitor
  {
    public ExecuteInsertManyGraphVisitor(Executor<TDbCommand> executor, TDbCommand command)
      : base(executor, command)
    {
    }

    public override Task<bool> VisitRootAsync(object root, IEntityModel model, CancellationToken cancellationToken = default)
    {
      return Task.FromResult(true);
    }
  }
}
