using CodeArchitects.Platform.Data.AdoNet.Model;
using System.Data.Common;

namespace CodeArchitects.Platform.Data.AdoNet.Executor;

internal partial class Executor
{
  public async Task ExecuteUpsertCommandAsync<TEntity, TKey>(DbCommand command, TEntity entity, IEntityModel<TEntity, TKey> model, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    _commandBuilder.BuildUpsertCommand(command, entity, model);

    object? result = await command.ExecuteScalarAsync(cancellationToken);
    if (model.AutoGeneratedColumn is { } autoGeneratedColumn && result is not null)
    {
      autoGeneratedColumn.SetValue(entity, result);
    }
  }
}
