using CodeArchitects.Platform.Data.AdoNet.Command;
using CodeArchitects.Platform.Data.AdoNet.Materialization;
using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Navigation;
using CodeArchitects.Platform.Data.Tracking;
using System.Collections;
using System.Data;
using System.Data.Common;

namespace CodeArchitects.Platform.Data.AdoNet.Executor;

internal class Executor : IExecutor
{
  private readonly ICommandBuilder _commandBuilder;
  private readonly IMaterializer _materializer;
  private readonly ITrackingContext _trackingContext;

  public Executor(ICommandBuilder commandBuilder, IMaterializer materializer, ITrackingContext trackingContext)
  {
    _commandBuilder = commandBuilder;
    _materializer = materializer;
    _trackingContext = trackingContext;
  }

  public async Task<TEntity?> ExecuteSelectCommandAsync<TEntity, TKey>(DbConnection connection, TKey key, NavigationSpec<TEntity, TKey> spec, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    using DbCommand command = connection.CreateCommand();
    _commandBuilder.BuildSelectCommand(command, key, spec);

    DbDataReader reader = await command.ExecuteReaderAsync(cancellationToken);
    
    return await _materializer.ReadEntityAsync(reader, spec, cancellationToken);
  }

  public async Task ExecuteInsertCommandAsync<TEntity, TKey>(DbConnection connection, TEntity entity, IEntityModel<TEntity, TKey> model, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    using DbCommand command = connection.CreateCommand();

    AsyncVisitNodeCallback<VisitGraphState> callback = static async delegate (object node, IEntityModel model, NavigationContext context, VisitGraphState state, CancellationToken cancellationToken)
    {
      (Executor self, DbCommand command) = state;
      (object parent, INavigationModel navigationModel) = context;

      if (navigationModel.IsOnDependent && navigationModel.IsAggregation)
      {
        await self.ExecuteInsertCommandAsync(command, node, model, in context, cancellationToken);
        return true;
      }
      
      if (navigationModel is ISkipNavigationModel skipNavigationModel)
      {
        object joinEntity = skipNavigationModel.CreateJoin(parent, node);
        await self.ExecuteInsertCommandAsync(command, joinEntity, skipNavigationModel.JoinEntity, default, cancellationToken);
      }

      return false;
    };

    await ExecuteInsertCommandAsync(command, entity, model, default, cancellationToken);
    await VisitGraphAsync(entity, model, new VisitGraphState(this, command), callback, cancellationToken);
  }

  public Task ExecuteUpdateCommandAsync<TEntity, TKey>(DbConnection connection, TEntity entity, IEntityModel<TEntity, TKey> model, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    throw new NotImplementedException();
  }

  public Task ExecuteDeleteCommandAsync<TEntity, TKey>(DbConnection connection, TKey key, IEntityModel<TEntity, TKey> model, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    throw new NotImplementedException();
  }

  private Task ExecuteInsertCommandAsync(DbCommand command, object node, IEntityModel model, in NavigationContext context, CancellationToken cancellationToken)
  {
    _commandBuilder.BuildInsertCommand(command, node, model, in context);

    return ExecuteAsync(command, node, model, cancellationToken);

    static async Task ExecuteAsync(DbCommand command, object entity, IEntityModel model, CancellationToken cancellationToken)
    {
      object? result = await command.ExecuteScalarAsync(cancellationToken);
      if (model.PrimaryKey.AutoGeneratedProperty is { } autoGeneratedProperty)
      {
        autoGeneratedProperty.SetValue(entity, result);
      }
    }
  }

  private Task ExecuteUpdateCommandAsync(DbCommand command, object node, IEntityModel model, in NavigationContext context, CancellationToken cancellationToken)
  {
    _commandBuilder.BuildUpdateCommand(command, node, model, in context);

    return ExecuteAsync(command, cancellationToken);

    static async Task ExecuteAsync(DbCommand command, CancellationToken cancellationToken)
    {
      int affectedRows = await command.ExecuteNonQueryAsync(cancellationToken);
      if (affectedRows == 0)
        throw new DBConcurrencyException(); // TODO: Message
    }
  }

  public void VisitGraph<TState>(object node, IEntityModel model, TState state, VisitNodeCallback<TState> callback)
  {
    foreach (INavigationModel navigationModel in model.Navigations)
    {
      if (!navigationModel.HasMember)
        continue;

      object? child = navigationModel.GetValue(node);
      if (child is null)
        continue;

      if (navigationModel.IsCollection)
      {
        IEnumerable collection = (IEnumerable)child;
        foreach (object element in collection)
        {
          bool continueTracking = callback(element, navigationModel.To, new NavigationContext(node, navigationModel), state);
          if (!continueTracking)
            continue;

          VisitGraph(element, navigationModel.To, state, callback);
        }
      }
      else
      {
        bool continueTracking = callback(child, navigationModel.To, new NavigationContext(node, navigationModel), state);
        if (!continueTracking)
          continue;

        VisitGraph(child, navigationModel.To, state, callback);
      }
    }
  }

  public async Task VisitGraphAsync<TState>(object node, IEntityModel model, TState state, AsyncVisitNodeCallback<TState> callback, CancellationToken cancellationToken)
  {
    foreach (INavigationModel navigationModel in model.Navigations)
    {
      if (!navigationModel.HasMember)
        continue;

      object? child = navigationModel.GetValue(node);
      if (child is null)
        continue;

      if (navigationModel.IsCollection)
      {
        IEnumerable collection = (IEnumerable)child;
        foreach (object element in collection)
        {
          bool continueTracking = await callback(element, navigationModel.To, new NavigationContext(node, navigationModel), state, cancellationToken);
          if (!continueTracking)
            continue;

          await VisitGraphAsync(element, navigationModel.To, state, callback, cancellationToken);
        }
      }
      else
      {
        bool continueTracking = await callback(child, navigationModel.To, new NavigationContext(node, navigationModel), state, cancellationToken);
        if (!continueTracking)
          continue;

        await VisitGraphAsync(child, navigationModel.To, state, callback, cancellationToken);
      }
    }
  }

  private readonly record struct VisitGraphState(Executor Self, DbCommand Command);
}
