using CodeArchitects.Platform.Data.AdoNet.Model;
using System.Data.Common;
using System.Diagnostics;

namespace CodeArchitects.Platform.Data.AdoNet.Executor;

internal partial class Executor
{
  public async Task ExecuteInsertCommandAsync<TEntity, TKey>(DbCommand command, TEntity entity, IEntityModel<TEntity, TKey> model, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    AsyncVisitNodeCallback<VisitGraphState> callback = static async delegate (object node, IEntityModel model, NavigationContext context, VisitGraphState state, CancellationToken cancellationToken)
    {
      (Executor self, DbCommand command) = state;
      (object parent, INavigationModel navigationModel) = context;

      switch (navigationModel)
      {
        case IAccessibleSimpleNavigationModel simpleNavigationModel:
          if (simpleNavigationModel.IsOnDependent)
            return false;

          if (simpleNavigationModel.AssociationKind is AssociationKind.Aggregation)
          {
            await self.ExecuteInsertCommandAsync(command, node, model, in context, cancellationToken);
            return true;
          }
          else
          {
            await self.ExecuteUpdateCommandAsync(command, node, simpleNavigationModel.NavigationEntity, in context, cancellationToken);
            return false;
          }

        case IAccessibleSkipNavigationModel skipNavigationModel:
          object joinEntity = skipNavigationModel.CreateJoin(parent, node);
          await self.ExecuteInsertCommandAsync(command, joinEntity, skipNavigationModel.JoinEntity, default, cancellationToken);
          return false;
        
        default:
          Debug.Fail("This point should be unreacheable.");
          return false;
      }
    };

    await ExecuteInsertCommandAsync(command, entity, model, default, cancellationToken);
    await VisitGraphAsync(entity, model, new VisitGraphState(this, command), callback, cancellationToken);
  }

  private Task ExecuteInsertCommandAsync(DbCommand command, object node, IEntityModel model, in NavigationContext context, CancellationToken cancellationToken)
  {
    _commandBuilder.BuildInsertCommand(command, node, model, in context);

    return ExecuteAsync(command, node, model, cancellationToken);

    static async Task ExecuteAsync(DbCommand command, object entity, IEntityModel model, CancellationToken cancellationToken)
    {
      object? result = await command.ExecuteScalarAsync(cancellationToken);
      if (model.AutoGeneratedColumn is { } autoGeneratedColumn && result is not null)
      {
        autoGeneratedColumn.SetValue(entity, result);
      }
    }
  }
}
