using CodeArchitects.Platform.Data.AdoNet.Interceptors;
using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.Features.Associations;
using System.Diagnostics;

namespace CodeArchitects.Platform.Data.AdoNet.Executor;

internal partial class Executor<TDbCommand>
{
  public async Task ExecuteInsertAsync<TEntity, TKey>(TDbCommand command, TEntity entity, IEntityModel<TEntity, TKey> model, CancellationToken cancellationToken)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    AsyncVisitNodeCallback<VisitGraphState> callback = static async delegate (object node, IEntityModel model, NavigationContext context, VisitGraphState state, CancellationToken cancellationToken)
    {
      (Executor<TDbCommand> self, TDbCommand command) = state;
      (object parent, INavigationModel navigationModel) = context;

      switch (navigationModel)
      {
        case IAccessibleSimpleNavigationModel simpleNavigationModel:
          if (simpleNavigationModel.IsOnDependent)
            return false;

          if (simpleNavigationModel.AssociationKind is AssociationKind.IntraAggregate)
          {
            await self.ExecuteInsertAsync(command, node, model, in context, cancellationToken);
            return true;
          }
          else
          {
            await self.ExecuteUpdateAsync(command, node, simpleNavigationModel.NavigationEntity, in context, cancellationToken);
            return false;
          }

        case IAccessibleSkipNavigationModel skipNavigationModel:
          object junctionEntity = skipNavigationModel.CreateJunction(parent, node);
          await self.ExecuteInsertAsync(command, junctionEntity, skipNavigationModel.JunctionEntity, default, cancellationToken);
          return false;
        
        default:
          Debug.Fail("This point should be unreachable.");
          return false;
      }
    };

    await ExecuteInsertAsync(command, entity, model, default, cancellationToken);
    await VisitGraphAsync(entity, model, new VisitGraphState(this, command), callback, cancellationToken);
  }

  private Task ExecuteInsertAsync(TDbCommand command, object node, IEntityModel model, in NavigationContext context, CancellationToken cancellationToken)
  {
    _commandBuilder.BuildInsertCommand(command, node, model, in context);
    _interceptor.OnCommandBuilt(OperationType.Insert, command);

    return ExecuteAsync(command, node, model, cancellationToken);

    static async Task ExecuteAsync(TDbCommand command, object entity, IEntityModel model, CancellationToken cancellationToken)
    {
      object? result = await command.ExecuteScalarAsync(cancellationToken);
      if (model.AutoGeneratedColumn is { } autoGeneratedColumn && result is not null)
      {
        autoGeneratedColumn.SetValue(entity, result);
      }
    }
  }
}
