using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Implementation;

internal abstract class ColumnModel : IColumnModel
{
  protected ColumnModel(short index)
  {
    Index = index;
  }

  public abstract bool IsPrimaryKey { get; }

  public abstract bool IsForeignKey { get; }

  public abstract string Name { get; }

  public bool IsAutoGenerated { get; set; }

  public short Index { get; }

  public abstract Type Type { get; }

  public abstract MemberInfo? Member { get; }

  public abstract FieldInfo? Field { get; }

  public abstract PropertyInfo? Property { get; }

  public abstract bool HasMember { get; }

  public abstract Getter<object?>? GetValue { get; }

  public abstract Setter<object?>? SetValue { get; }

  public abstract TResult Accept<TVisitor, TResult>(in TVisitor visitor)
    where TVisitor : IColumnModelVisitor<TResult>;

  public abstract TResult Accept<TVisitor, TResult, TState>(in TVisitor visitor, in TState state)
    where TVisitor : IColumnModelVisitor<TResult, TState>;
}
