namespace CodeArchitects.Platform.Data.AdoNet.Model.Implementation;

internal abstract class ColumnModel : MemberModel, IColumnModel
{
  protected ColumnModel(short index)
  {
    Index = index;
  }

  public abstract bool IsPrimaryKey { get; }

  public abstract bool IsForeignKey { get; }

  public abstract string Name { get; set; }

  public abstract bool IsConcurrencyToken { get; set; }

  public bool IsAutoGenerated { get; set; }

  public short Index { get; }

  public abstract TResult Accept<TResult>(IColumnModelVisitor<TResult> visitor);

  public abstract TResult Accept<TResult, TState>(IColumnModelVisitor<TResult, TState> visitor, in TState state);
}
