namespace CodeArchitects.Platform.Data.AdoNet.Model.Implementation;

internal abstract class ColumnModel : MemberModel, IColumnModel
{
  protected ColumnModel(short index)
  {
    Index = index;
  }

  public abstract bool IsPrimaryKey { get; }

  public abstract bool IsForeignKey { get; }

  public abstract string Name { get; set; }

  public bool IsAutoGenerated { get; set; }

  public short Index { get; }

  public abstract TResult Accept<TVisitor, TResult>(in TVisitor visitor)
    where TVisitor : IColumnModelVisitor<TResult>;

  public abstract TResult Accept<TVisitor, TResult, TState>(in TVisitor visitor, in TState state)
    where TVisitor : IColumnModelVisitor<TResult, TState>;
}
