using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Implementation;

internal abstract class EntityModel : IEntityModel
{
  private string? _tableName;
  private readonly List<ColumnModel> _columns;
  private readonly List<NavigationModel> _navigations;

  public EntityModel(InitializerModel initializer)
  {
    Initializer = initializer;
    _columns = new();
    _navigations = new();
  }

  [AllowNull]
  public string TableName
  {
    get => _tableName ?? Type.Name;
    set => _tableName = value;
  }

  public abstract Type Type { get; }

  public bool UsesConcurrencyChecks => ConcurrencyToken is not null;

  public InitializerModel Initializer { get; }

  public IAccessibleColumnModel? AutoGeneratedColumn { get; set; }

  public IAccessibleColumnModel? ConcurrencyToken { get; set; }

  public IReadOnlyCollection<ColumnModel> Columns => _columns;

  public IReadOnlyCollection<NavigationModel> Navigations => _navigations;

  public PrimaryKeyModel PrimaryKey => PrimaryKeyCore;

  protected abstract PrimaryKeyModel PrimaryKeyCore { get; }

  IInitializerModel IEntityModel.Initializer => Initializer;

  IReadOnlyCollection<IColumnModel> IEntityModel.Columns => Columns;

  IReadOnlyCollection<INavigationModel> IEntityModel.Navigations => Navigations;

  IPrimaryKeyModel IEntityModel.PrimaryKey => PrimaryKey;

  public void AddColumn(ColumnModel column)
  {
    _columns.Add(column);
  }

  public void AddNavigation(NavigationModel navigation)
  {
    _navigations.Add(navigation);
  }

  public bool TryGetColumn(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleColumnModel? column)
  {
    foreach (IColumnModel col in _columns)
    {
      if (!col.HasMember)
        continue;

      Debug.Assert(col is IAccessibleColumnModel, $"A column model with member should be assignable to {nameof(IAccessibleColumnModel)}.");

      if (name.SequenceEqual(col.Member.Name))
      {
        column = (IAccessibleColumnModel)col;
        return true;
      }
    }

    column = null;
    return false;
  }

  public bool TryGetNavigation(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleNavigationModel? navigation)
  {
    foreach (INavigationModel nav in Navigations)
    {
      if (!nav.HasMember)
        continue;

      Debug.Assert(nav is IAccessibleNavigationModel, $"A navigation model with member should be assignable to {nameof(IAccessibleNavigationModel)}.");

      if (name.SequenceEqual(nav.Member.Name))
      {
        navigation = (IAccessibleNavigationModel)nav;
        return true;
      }
    }

    navigation = null;
    return false;
  }

  public static EntityModel Create(Type entityType, InitializerModel initializer, PrimaryKeyModel primaryKey)
  {
    Type type = typeof(EntityModel<,>).MakeGenericType(entityType, primaryKey.Type);
    return (EntityModel)Activator.CreateInstance(type, new object[] { initializer, primaryKey })!;
  }
}
