using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Implementation;

internal abstract class EntityModel : IEntityModel
{
  private string? _name;
  private string? _tableName;
  private readonly List<ColumnModel> _columns;
  private readonly List<NavigationModel> _navigations;
  private readonly List<IForeignKeyModel> _foreignKeys;

  public EntityModel(InitializerModel initializer)
  {
    Initializer = initializer;
    _columns = new();
    _navigations = new();
    _foreignKeys = new();
  }

  [AllowNull]
  public string Name
  {
    get => _name ?? Type.Name;
    set => _name = value;
  }

  [AllowNull]
  public string TableName
  {
    get => _tableName ?? Type.Name;
    set => _tableName = value;
  }

  public abstract Type Type { get; }

  public InitializerModel Initializer { get; }

  public AccessibleColumnModel? AutoGeneratedColumn { get; set; }

  public IReadOnlyCollection<IForeignKeyModel> ForeignKeys => _foreignKeys;

  public IReadOnlyCollection<ColumnModel> Columns => _columns;

  public IReadOnlyCollection<NavigationModel> Navigations => _navigations;

  public IPrimaryKeyModel PrimaryKey => PrimaryKeyCore;

  protected abstract IPrimaryKeyModel PrimaryKeyCore { get; }

  public void AddColumn(ColumnModel column)
  {
    _columns.Add(column);
  }

  public bool TryGetNavigation(ReadOnlySpan<char> name, [NotNullWhen(true)] out AccessibleNavigationModel? navigation)
  {
    foreach (NavigationModel nav in Navigations)
    {
      if (!nav.HasMember)
        continue;

      Debug.Assert(nav is AccessibleNavigationModel, $"A navigation model with member should be assignable to {nameof(AccessibleNavigationModel)}.");

      if (name.SequenceEqual(nav.Member.Name.AsSpan()))
      {
        navigation = (AccessibleNavigationModel)nav;
        return true;
      }
    }

    navigation = null;
    return false;
  }

  #region Explicit implementation

  IInitializerModel IEntityModel.Initializer => Initializer;

  IReadOnlyCollection<IColumnModel> IEntityModel.Columns => Columns;

  IReadOnlyCollection<INavigationModel> IEntityModel.Navigations => Navigations;

  IAccessibleColumnModel? IEntityModel.AutoGeneratedColumn => AutoGeneratedColumn;

  bool IEntityModel.TryGetNavigation(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleNavigationModel? navigation)
  {
    if (TryGetNavigation(name, out AccessibleNavigationModel? nav))
    {
      navigation = nav;
      return true;
    }

    navigation = null;
    return false;
  }

  #endregion
}
