using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Implementation;

internal abstract class ForeignKeyColumnModel : IForeignKeyColumnModel
{
  public ForeignKeyColumnModel(short index, short foreignKeyIndex)
  {
    Index = index;
    ForeignKeyIndex = foreignKeyIndex;
  }

  protected abstract MemberModelComponent MemberComponent { get; }

  public short ForeignKeyIndex { get; }

  public IPrimaryKeyColumnModel PrimaryKeyColumn => throw new NotImplementedException();

  public INavigationModel Navigation => throw new NotImplementedException();

  public bool IsPrimaryKey => false;

  public bool IsForeignKey => true;

  public string Name => throw new NotImplementedException();

  public bool IsAutoGenerated { get; set; }

  public short Index { get; }

  public Type Type => throw new NotImplementedException();

  public MemberInfo? Member => MemberComponent.Member;

  public FieldInfo? Field => MemberComponent.Field;

  public PropertyInfo? Property => MemberComponent.Property;

  public bool HasMember => MemberComponent.HasMember;

  public Getter<object?>? GetValue => MemberComponent.GetValue;

  public Setter<object?>? SetValue => MemberComponent.SetValue;

  public TResult Accept<TVisitor, TResult>(in TVisitor visitor)
    where TVisitor : IColumnModelVisitor<TResult>
  {
    return visitor.VisitForeignKey(this);
  }

  public TResult Accept<TVisitor, TResult, TState>(in TVisitor visitor, in TState state)
    where TVisitor : IColumnModelVisitor<TResult, TState>
  {
    return visitor.VisitForeignKey(this, in state);
  }
}
