using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Implementation;

internal class JoinEntityModel : IEntityModel
{
  private readonly List<IColumnModel> _columns;

  public JoinEntityModel(string tableName)
  {
    _columns = new();
    TableName = tableName;
  }

  public string TableName { get; }

  public Type Type => typeof(Dictionary<string, object>);

  public IInitializerModel Initializer => throw new NotSupportedException("Join entities do not have an initializer.");

  public IAccessibleColumnModel? AutoGeneratedColumn => null;

  public IPrimaryKeyModel PrimaryKey => throw new NotImplementedException();

  public IReadOnlyCollection<IColumnModel> Columns => throw new NotImplementedException();

  public IReadOnlyCollection<INavigationModel> Navigations => Array.Empty<INavigationModel>();

  public bool TryGetColumn(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleColumnModel? column)
  {
    foreach (IColumnModel col in _columns)
    {
      if (!col.HasMember)
        continue;

      Debug.Assert(col is IAccessibleColumnModel, $"A column model with member should be assignable to {nameof(IAccessibleColumnModel)}.");

      if (name.SequenceEqual(col.Member.Name))
      {
        column = (IAccessibleColumnModel)col;
        return true;
      }
    }

    column = null;
    return false;
  }

  public bool TryGetNavigation(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleNavigationModel? navigation)
  {
    navigation = null;
    return false;
  }
}
