using System.Diagnostics.CodeAnalysis;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Implementation;

internal class JoinEntityModel : IEntityModel
{
  public JoinEntityModel(string tableName)
  {
    TableName = tableName;
  }

  public string TableName { get; }

  public Type Type => typeof(Dictionary<string, object>);

  public IInitializerModel Initializer => throw new NotSupportedException("Join entities do not have an initializer.");

  public IAccessibleColumnModel? AutoGeneratedColumn => null;

  public IPrimaryKeyModel PrimaryKey => throw new NotImplementedException();

  public IReadOnlyCollection<IForeignKeyModel> ForeignKeys => throw new NotImplementedException();

  public IReadOnlyCollection<IColumnModel> Columns => throw new NotImplementedException();

  public IReadOnlyCollection<INavigationModel> Navigations => Array.Empty<INavigationModel>();

  public bool TryGetNavigation(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleNavigationModel? navigation)
  {
    navigation = null;
    return false;
  }
}
