using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Implementation;

internal class NavigationEntityModel : IEntityModel
{
  private readonly IEntityModel _entity;

  public NavigationEntityModel(IEntityModel entity, IReadOnlyCollection<IColumnModel> columns)
  {
    _entity = entity;
    Columns = columns;
  }

  public string TableName => _entity.TableName;

  public Type Type => _entity.Type;

  public IInitializerModel Initializer => throw new NotSupportedException("Navigation entities do not have an initializer component.");

  public IAccessibleColumnModel? AutoGeneratedColumn => null;

  public IPrimaryKeyModel PrimaryKey => _entity.PrimaryKey;

  public IReadOnlyCollection<IColumnModel> Columns { get; }

  public IReadOnlyCollection<INavigationModel> Navigations => throw new NotSupportedException("Navigation entities do not have navigation components.");

  public bool TryGetColumn(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleColumnModel? column)
  {
    foreach (IColumnModel col in Columns)
    {
      if (!col.HasMember)
        continue;

      Debug.Assert(col is IAccessibleColumnModel, $"A column model with member should be assignable to {nameof(IAccessibleColumnModel)}.");

      if (name.SequenceEqual(col.Member.Name))
      {
        column = (IAccessibleColumnModel)col;
        return true;
      }
    }

    column = null;
    return false;
  }

  public bool TryGetNavigation(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleNavigationModel? navigation)
  {
    throw new NotSupportedException("A navigation entity does not have navigation components.");
  }

  public static NavigationEntityModel Create(ISimpleNavigationModel navigation)
  {
    IEnumerable<IColumnModel> foreignKeyColumns = navigation.KeyPairs.Select(pair => pair.ForeignKeyColumn);
    IReadOnlyCollection<IColumnModel> columns = navigation.To.PrimaryKey.Columns
      .Concat(foreignKeyColumns)
      .ToList();

    return new(navigation.To, columns);
  }
}
