using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Implementation;

internal class OrdinaryColumnModel : IOrdinaryColumnModel
{
  private readonly AccessibleMemberModelComponent _memberComponent;
  private string? _name;

  public OrdinaryColumnModel(AccessibleMemberModelComponent memberComponent, short index)
  {
    _memberComponent = memberComponent;
    Index = index;
  }

  public bool IsPrimaryKey => false;

  public bool IsForeignKey => false;

  public string Name { get => _name ?? Member.Name; set => _name = value; }

  public bool IsAutoGenerated { get; set; }

  public short Index { get; }

  public MemberInfo Member => _memberComponent.Member;

  public Getter<object?> GetValue => _memberComponent.GetValue;

  public Setter<object?> SetValue => _memberComponent.SetValue;

  public Type Type => _memberComponent.Type;

  public FieldInfo? Field => _memberComponent.Field;

  public PropertyInfo? Property => _memberComponent.Property;

  public bool HasMember => _memberComponent.HasMember;

  public TResult Accept<TVisitor, TResult>(in TVisitor visitor)
    where TVisitor : IColumnModelVisitor<TResult>
  {
    return visitor.VisitOrdinary(this);
  }

  public TResult Accept<TVisitor, TResult, TState>(in TVisitor visitor, in TState state)
    where TVisitor : IColumnModelVisitor<TResult, TState>
  {
    return visitor.VisitOrdinary(this, in state);
  }
}
