using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Implementation;

internal class PrimaryKeyColumnModel : IPrimaryKeyColumnModel
{
  private readonly AccessibleMemberModelComponent _memberComponent;

  public PrimaryKeyColumnModel(AccessibleMemberModelComponent memberComponent, short index, short primaryKeyIndex)
  {
    _memberComponent = memberComponent;
    Index = index;
    PrimaryKeyIndex = primaryKeyIndex;
  }

  public short PrimaryKeyIndex { get; }

  public bool IsPrimaryKey => true;

  public bool IsForeignKey => false;

  public string Name => Member.Name;

  public bool IsAutoGenerated { get; set; }

  public short Index { get; }

  public MemberInfo Member => _memberComponent.Member;

  public Getter<object?> GetValue => _memberComponent.GetValue;

  public Setter<object?> SetValue => _memberComponent.SetValue;

  public Type Type => _memberComponent.Type;

  public FieldInfo? Field => _memberComponent.Field;

  public PropertyInfo? Property => _memberComponent.Property;

  public bool HasMember => _memberComponent.HasMember;

  public TResult Accept<TVisitor, TResult>(in TVisitor visitor)
    where TVisitor : IColumnModelVisitor<TResult>
  {
    return visitor.VisitPrimaryKey(this);
  }

  public TResult Accept<TVisitor, TResult, TState>(in TVisitor visitor, in TState state)
    where TVisitor : IColumnModelVisitor<TResult, TState>
  {
    return visitor.VisitPrimaryKey(this, in state);
  }
}
