parameters:
- name: workDir
  type: string
  default: $(System.DefaultWorkingDirectory)

steps:
- task: PowerShell@2
  displayName: nuget login
  inputs:
    workingDirectory: ${{ parameters.workDir }}
    targetType: 'inline'
    script: |
      dotnet nuget add source $(SOURCE) -n $(SOURCE_NAME) -u "AzureDevOps" -p "$(System.AccessToken)" --store-password-in-clear-text --valid-authentication-types basic --configfile NuGet.Config