parameters:
- name: workDir
  displayName: workDir
  type: string
  default: $(System.DefaultWorkingDirectory)
- name: condition
  displayName: condition
  type: string
- name: nupkgList
  type: object
  default: ['Actors','Actors.Dapr','Actors.Dapr.AspNetCore','Application','Common','Dapr.AspNetCore','Data','Data.AdoNet','Data.AdoNet.DependencyInjection','Data.AdoNet.MySQL','Data.AdoNet.Oracle','Data.AdoNet.PostgreSQL','Data.AdoNet.SQLServer','Data.AutoMapper','Data.EntityFrameworkCore','Data.EntityFrameworkCore.DependencyInjection','Data.EntityFrameworkCore.Shared','Data.EntityFrameworkCore5','Data.EntityFrameworkCore5.DependencyInjection','Data.MongoDB','Data.MongoDB.DependencyInjection','Emit','Extensions','Infrastructure','Infrastructure.Dapr','Infrastructure.Dapr.AspNetCore','Messaging','Messaging.AspNetCore','Messaging.Dapr','Messaging.Dapr.AspNetCore'] # this array contain the list of csproj files to pack
- name: prefix
  type: string
  default: 'CodeArchitects.Platform'
steps:
- ${{ each nupkg in parameters.nupkgList }}:
  - task: PowerShell@2
    condition: ${{ parameters.condition }}
    displayName: Check package availability
    inputs:
      targetType: 'inline'
      workingDirectory: ${{ parameters.workDir }}
      script: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

        $user = "$(SA)"
        $token = "$(TOKEN)"
        $base64auth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $user, $token )))
        $header = @{"Accept" = "*/*"; Authorization = ("Basic {0}" -f $base64auth) }
        $password = ConvertTo-SecureString $token -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($user, $password)

        $pkgDest = $env:REGISTRY_LIST
        $pkgDest = $pkgDest.Split(',')
        $version = "$(Build.BuildNumber)"

        $methods = @( "Head", "Get" )
        $domain = "https://devops.codearchitects.com:444/Code%20Architects/_apis/packaging/feeds"

        foreach ( $registry in $pkgDest ){
          Write-Host "Checking for $registry registry..."
          $uri = "$domain/$registry/nuget/packages/${{ parameters.prefix }}.${{ nupkg }}/versions/$(Build.BuildNumber)/content?api-version=5.0-preview.1"
          Write-Host "Uri: $uri"
          foreach ( $method in $methods ) {
            $response = $(Invoke-WebRequest -Method $method -Headers $header -Credential $credential -Uri $uri)
            Write-Host "response for $registry with $method : $($response.StatusCode) $($response.StatusDescription)"
          }
        }
