parameters:
- name: workDir
  type: string
  default: $(System.DefaultWorkingDirectory)
- name: solution
  displayName: solution
  type: string
- name: buildConfiguration
  displayName: buildConfiguration
  type: string
  default: Release

steps:
- task: PowerShell@2
  displayName: build ${{ parameters.solution }}
  inputs:
    workingDirectory: ${{ parameters.workDir }}
    targetType: inline
    script: |
      dotnet build ${{ parameters.solution }} -c ${{ parameters.buildConfiguration }} --no-restore
    