parameters:
- name: solution
  type: string
- name: workDir
  type: string
  default: $(System.DefaultWorkingDirectory)

steps:
- task: Powershell@2
  displayName: dotnet restore ${{ parameters.solution }}
  inputs:
    targetType: 'inline'
    script: |
      dotnet clean ${{parameters.solution}} -c Release
      dotnet restore ${{parameters.solution}} --configfile ./NuGet.Config --no-cache