steps:
- task: PowerShell@2
  displayName: install sign tool
  inputs:
    workingDirectory: ${{ parameters.workDir }}
    targetType: inline
    script: |
      dotnet tool install --global sign --version 0.9.1-beta.26301.2
      #0.9.1-beta.25228.1