using CodeArchitects.Platform.Data.AdoNet;
using CodeArchitects.Platform.Data.Fixtures.Model;

namespace CodeArchitects.Platform.Data.Fixtures;

internal class TestModelConfiguration : ModelConfiguration
{
  protected override void Configure()
  {
    Entity<Cart>();

    Entity<CartItem>(entity => entity
      .WithKey(item => new { item.Index, item.CartId }));

    Entity<Product>();

    Entity<ShippingAddress>();

    Entity<Category>();

    Entity<Typology>();

    Entity<Customer>();

    Entity<Address>();

    Entity<CustomerClaim>();

    Entity<Person>();

    Entity<SerialEntity>(entity => entity
      .WithAutoGeneratedColumn(e => e.Id));

    Aggregate<Cart, CartItem>(aggregate => aggregate
      .OneToMany()
      .Navigation(cart => cart.Items)
      .InverseNavigation(item => item.Cart)
      .UsingForeignKey(item => item.CartId));

    Associate<Customer, Cart>(associate => associate
      .OneToMany()
      .Navigation(customer => customer.Carts)
      .InverseNavigation(cart => cart.Customer)
      .UsingForeignKey(Column("CustomerId")));

    Associate<ShippingAddress, CartItem>(associate => associate
      .OneToMany()
      .InverseNavigation(item => item.ShippingAddress)
      .UsingForeignKey(Column("ShippingAddressId")));

    Associate<CartItem, Product>(associate => associate
      .ManyToMany()
      .Navigation(item => item.Products)
      .UsingJunctionTable("CartItemProduct")
      .UsingJunctionColumnNames("CartItemIndex", "CartItemCartId", "ProductId"));

    Associate<Category, Product>(associate => associate
      .OneToMany()
      .InverseNavigation(product => product.Category)
      .UsingForeignKey(Column("CategoryId")));

    Associate<Typology, Product>(associate => associate
      .OneToMany()
      .InverseNavigation(product => product.Typology)
      .UsingForeignKey(Column("TypologyId")));

    Associate<Category, Typology>(associate => associate
      .ManyToMany()
      .Navigation(category => category.Typologies)
      .InverseNavigation(typology => typology.Categories)
      .UsingJunctionTable("CategoryTypology")
      .UsingJunctionColumnNames("CategoryId", "TypologyId"));

    Aggregate<Customer, Address>(aggregate => aggregate
      .OneToOne()
      .Navigation(customer => customer.Address)
      .InverseNavigation(address => address.Customer)
      .UsingForeignKey(Column("CustomerId")));

    Aggregate<Customer, CustomerClaim>(aggregate => aggregate
      .OneToMany()
      .Navigation(customer => customer.Claims)
      .UsingForeignKey(Column("CustomerId")));

    Associate<Person, Person>(associate => associate
      .OneToOne()
      .Navigation(person => person.Partner)
      .InverseNavigation(person => person.Partner)
      .UsingForeignKey(Column("PartnerId")));
  }
}
