using CodeArchitects.Platform.Data.AdoNet;
using CodeArchitects.Platform.Data.Fixtures.Model;

namespace CodeArchitects.Platform.Data.Fixtures;

internal class TestModelConfiguration : ModelConfiguration
{
  protected override void Configure()
  {
    Entity<Cart>();

    Entity<CartItem>(entity => entity
      .WithKey(item => new { item.Index, item.CartId }));

    Entity<Product>();

    Entity<ShippingAddress>();

    Entity<Category>();

    Entity<Typology>();

    Entity<Customer>();

    Entity<Address>();

    Entity<CustomerClaim>();

    Entity<Person>();

    Entity<SerialEntity>(entity => entity
      .WithAutoGeneratedColumn(e => e.Id));

    Aggregation<Cart, CartItem>(aggregation => aggregation
      .OneToMany()
      .Navigation(cart => cart.Items)
      .InverseNavigation(item => item.Cart)
      .UsingForeignKey(item => item.CartId));

    Composition<Customer, Cart>(composition => composition
      .OneToMany()
      .Navigation(customer => customer.Carts)
      .InverseNavigation(cart => cart.Customer)
      .UsingForeignKey(Column("CustomerId")));

    Composition<ShippingAddress, CartItem>(composition => composition
      .OneToMany()
      .InverseNavigation(item => item.ShippingAddress)
      .UsingForeignKey(Column("ShippingAddressId")));

    Composition<CartItem, Product>(composition => composition
      .ManyToMany()
      .Navigation(item => item.Products)
      .UsingJunctionTable("CartItemProduct")
      .UsingJunctionColumnNames("CartItemIndex", "CartItemCartId", "ProductId"));

    Composition<Category, Product>(composition => composition
      .OneToMany()
      .InverseNavigation(product => product.Category)
      .UsingForeignKey(Column("CategoryId")));

    Composition<Typology, Product>(composition => composition
      .OneToMany()
      .InverseNavigation(product => product.Typology)
      .UsingForeignKey(Column("TypologyId")));

    Composition<Category, Typology>(composition => composition
      .ManyToMany()
      .Navigation(category => category.Typologies)
      .InverseNavigation(typology => typology.Categories)
      .UsingJunctionTable("CategoryTypology")
      .UsingJunctionColumnNames("CategoryId", "TypologyId"));

    Aggregation<Customer, Address>(aggregation => aggregation
      .OneToOne()
      .Navigation(customer => customer.Address)
      .InverseNavigation(address => address.Customer)
      .UsingForeignKey(Column("CustomerId")));

    Aggregation<Customer, CustomerClaim>(aggregation => aggregation
      .OneToMany()
      .Navigation(customer => customer.Claims)
      .UsingForeignKey(Column("CustomerId")));

    Composition<Person, Person>(composition => composition
      .OneToOne()
      .Navigation(person => person.Partner)
      .InverseNavigation(person => person.Partner)
      .UsingForeignKey(Column("PartnerId")));
  }
}
