using CodeArchitects.Platform.Data.Fixtures;
using CodeArchitects.Platform.Data.Fixtures.Model;
using Microsoft.EntityFrameworkCore;
using Xunit.Abstractions;

namespace CodeArchitects.Platform.Data;

[Collection(TestCollection.Name)]
public class InsertManyAsyncTests : TestBase
{
  public InsertManyAsyncTests(TestFixture fixture, ITestOutputHelper output)
    : base(fixture, output)
  {
  }

  [Theory, RepositoryDependenciesData]
  public async Task InsertManyAsync_ShouldSetAutogeneratedColumn_WhenEntityHasAutogeneratedColumn(RepositoryDependencies dependencies)
  {
    // Arrange
    List<SerialEntity> entities = SerialEntity.Many(2);

    var sut = _fixture.CreateRepository<SerialEntity, int>(dependencies);

    // Act
    await sut.InsertManyAsync(entities);

    // Assert
    SerialEntity?[] fromDb = new[]
    {
      _fixture.DbContext.Set<SerialEntity>().FirstOrDefault(x => x.Id == entities[0].Id),
      _fixture.DbContext.Set<SerialEntity>().FirstOrDefault(x => x.Id == entities[1].Id),
    };

    fromDb[0].Should().NotBeNull();
    fromDb[1].Should().NotBeNull();
    entities[0].Id.Should().NotBe(0).And.Be(fromDb[0]!.Id);
    entities[1].Id.Should().NotBe(0).And.Be(fromDb[1]!.Id);
  }

  [Theory, RepositoryDependenciesData]
  public async Task InsertManyAsync_ShouldInsertEntityAndAddLinks_WhenNavigationIsManyToMany(RepositoryDependencies dependencies)
  {
    // Arrange
    Typology typology = Typology.One();
    List<Category> categories = Category.Many(2);
    categories[0].Typologies = new() { typology };
    categories[1].Typologies = new() { typology };

    var sut = _fixture.CreateRepository<Category, Guid>(dependencies, seeder => seeder.Seed(typology));

    // Act
    await sut.InsertManyAsync(categories);

    // Assert
    IQueryable<Category> queryable = _fixture.DbContext.Set<Category>().Include(x => x.Typologies);
    Category?[] fromDb = new[]
    {
      queryable.FirstOrDefault(x => x.Id == categories[0].Id),
      queryable.FirstOrDefault(x => x.Id == categories[1].Id)
    };

    fromDb[0].Should().NotBeNull();
    fromDb[0]!.Typologies.Should().HaveCount(1)
      .And.ContainSingle(t => t.Id == typology.Id && t.Name == typology.Name);
    fromDb[1].Should().NotBeNull();
    fromDb[1]!.Typologies.Should().HaveCount(1)
      .And.ContainSingle(t => t.Id == typology.Id && t.Name == typology.Name);
  }

  [Theory, RepositoryDependenciesData]
  public async Task InsertManyAsync_ShouldInsertEntityAndAddLinks_WhenNavigationIsOneToManyInterAggregate(RepositoryDependencies dependencies)
  {
    // Arrange
    List<Customer> customers = Customer.Many(2);
    Cart cart0 = Cart.One();
    cart0.Items = CartItem.Many(1, cart0.Id);
    customers[0].Carts = new() { cart0 };
    Cart cart1 = Cart.One();
    cart1.Items = CartItem.Many(1, cart1.Id);
    customers[1].Carts = new() { cart1 };

    var sut = _fixture.CreateRepository<Customer, Guid>(dependencies, seeder => seeder.Seed(cart0, cart1));

    // Act
    await sut.InsertManyAsync(customers);

    // Assert
    IQueryable<Customer> queryable = _fixture.DbContext.Set<Customer>().Include(x => x.Carts);
    Customer?[] fromDb = new[]
    {
      queryable.FirstOrDefault(x => x.Id == customers[0].Id),
      queryable.FirstOrDefault(x => x.Id == customers[1].Id)
    };

    fromDb[0].Should().NotBeNull();
    fromDb[0]!.Carts.Should().HaveCount(1)
      .And.ContainSingle(c => c.Id == cart0.Id && c.Name == cart0.Name);
    fromDb[1]!.Carts.Should().HaveCount(1)
      .And.ContainSingle(c => c.Id == cart1.Id && c.Name == cart1.Name);
  }

  [Theory, RepositoryDependenciesData]
  public async Task InsertManyAsync_ShouldInsertEntityAndAddLinks_WhenNavigationIsOneToOneInterAggregate(RepositoryDependencies dependencies)
  {
    // Arrange
    List<Person> firsts = Person.Many(2);
    List<Person> seconds = Person.Many(2);
    seconds[0].Partner = firsts[0];
    seconds[1].Partner = firsts[1];

    var sut = _fixture.CreateRepository<Person, Guid>(dependencies, seeder => seeder.Seed(firsts));

    // Act
    await sut.InsertManyAsync(seconds);

    // Assert
    IQueryable<Person> queryable = _fixture.DbContext.Set<Person>().Include(x => x.Partner);
    Person?[] fromDb = new[]
    {
      queryable.FirstOrDefault(x => x.Id == seconds[0].Id),
      queryable.FirstOrDefault(x => x.Id == seconds[1].Id)
    };

    fromDb[0].Should().NotBeNull();
    fromDb[0]!.Partner.Should().NotBeNull();
    fromDb[1].Should().NotBeNull();
    fromDb[1]!.Partner.Should().NotBeNull();
  }

  [Theory, RepositoryDependenciesData]
  public async Task InsertManyAsync_ShouldInsertEntityAndChildren_WhenNavigationIsOneToManyIntraAggregate(RepositoryDependencies dependencies)
  {
    // Arrange
    List<Cart> carts = Cart.Many(2);
    CartItem item0 = CartItem.One(carts[0].Id);
    carts[0].Items = new() { item0 };
    CartItem item1 = CartItem.One(carts[1].Id);
    carts[1].Items = new() { item1 };

    var sut = _fixture.CreateRepository<Cart, Guid>(dependencies);

    // Act
    await sut.InsertManyAsync(carts);

    // Assert
    IQueryable<Cart> queryable = _fixture.DbContext.Set<Cart>().Include(x => x.Items);
    Cart?[] fromDb = new[]
    {
      queryable.FirstOrDefault(x => x.Id == carts[0].Id),
      queryable.FirstOrDefault(x => x.Id == carts[1].Id)
    };

    fromDb[0].Should().NotBeNull();
    fromDb[0]!.Items.Should().HaveCount(1)
      .And.ContainSingle(i => i.Index == item0.Index && i.CartId == item0.CartId && i.Name == item0.Name);
    fromDb[1].Should().NotBeNull();
    fromDb[1]!.Items.Should().HaveCount(1)
      .And.ContainSingle(i => i.Index == item1.Index && i.CartId == item1.CartId && i.Name == item1.Name);
  }

  [Theory, RepositoryDependenciesData]
  public async Task InsertManyAsync_ShouldInsertEntityAndChild_WhenNavigationIsOneToOneIntraAggregate(RepositoryDependencies dependencies)
  {
    // Arrange
    List<Customer> customers = Customer.Many(2);
    customers[0].Address = Address.One();
    customers[1].Address = Address.One();

    var sut = _fixture.CreateRepository<Customer, Guid>(dependencies);

    // Act
    await sut.InsertManyAsync(customers);

    // Assert
    IQueryable<Customer> queryable = _fixture.DbContext.Set<Customer>().Include(x => x.Address);
    Customer?[] fromDb = new[]
    {
      queryable.FirstOrDefault(x => x.Id == customers[0].Id),
      queryable.FirstOrDefault(x => x.Id == customers[1].Id)
    };

    fromDb[0].Should().NotBeNull();
    fromDb[0]!.Address.Should().NotBeNull();
    fromDb[1].Should().NotBeNull();
    fromDb[1]!.Address.Should().NotBeNull();
  }
}
