using CodeArchitects.Platform.CodeAnalysis;

namespace CodeArchitects.Platform.Data.AdoNet.Model;

[Experimental]
public interface IColumnModel : IPropertyModelBase
{
  bool IsPrimaryKey { get; }

  bool IsForeignKey { get; }

  string Name { get; }

  bool IsAutoGenerated { get; }

  short Index { get; }

  TResult Accept<TVisitor, TResult>(in TVisitor visitor)
    where TVisitor : IColumnModelVisitor<TResult>;

  TResult Accept<TVisitor, TResult, TState>(in TVisitor visitor, in TState state)
    where TVisitor : IColumnModelVisitor<TResult, TState>;
}
