using CodeArchitects.Platform.CodeAnalysis;

namespace CodeArchitects.Platform.Data.AdoNet.Model;

/// <summary>
/// Represents a database column in an entity model.
/// </summary>
[Experimental]
public interface IColumnModel : IMemberModel
{
  /// <summary>
  /// Indicates whether this column is a primary key in the entity model.
  /// </summary>
  bool IsPrimaryKey { get; }

  /// <summary>
  /// Indicates whether this column is a foreign key in the entity model.
  /// </summary>
  bool IsForeignKey { get; }

  /// <summary>
  /// The name of this column.
  /// </summary>
  string Name { get; }

  /// <summary>
  /// Indicates whether this column is auto-generated by the database.
  /// </summary>
  bool IsAutoGenerated { get; }

  /// <summary>
  /// The index of this column within all columns of the entity.
  /// </summary>
  short Index { get; }

  /// <summary>
  /// Dispatches to the specific visit method for this column type.
  /// </summary>
  /// <typeparam name="TVisitor">The visitor type.</typeparam>
  /// <typeparam name="TResult">The result type.</typeparam>
  /// <param name="visitor">The visitor.</param>
  /// <returns>The result produced by the visitor.</returns>
  TResult Accept<TVisitor, TResult>(in TVisitor visitor)
    where TVisitor : IColumnModelVisitor<TResult>;

  /// <summary>
  /// Dispatches to the specific visit method for this column type.
  /// </summary>
  /// <typeparam name="TVisitor">The visitor type.</typeparam>
  /// <typeparam name="TResult">The result type.</typeparam>
  /// <typeparam name="TState">The type of the state object passed to the visitor.</typeparam>
  /// <param name="visitor">The visitor.</param>
  /// <param name="state">The state object to pass to the visitor.</param>
  /// <returns>The result produced by the visitor.</returns>
  TResult Accept<TVisitor, TResult, TState>(in TVisitor visitor, in TState state)
    where TVisitor : IColumnModelVisitor<TResult, TState>;
}
