extern alias CaPlatformCommon;
using CaPlatformCommon.CodeArchitects.Platform.Common.CodeAnalysis;
using System.Diagnostics.CodeAnalysis;

namespace CodeArchitects.Platform.Data.AdoNet.Model;

/// <summary>
/// Represents a model for a database entity.
/// </summary>
[Experimental]
public interface IEntityModel
{
  /// <summary>
  /// The name of the table in the database that represents this entity.
  /// </summary>
  string TableName { get; }

  /// <summary>
  /// The type of the entity.
  /// </summary>
  Type Type { get; }

  /// <summary>
  /// Indicates whether the entities uses optimistic concurrency checks.
  /// </summary>
  [MemberNotNullWhen(true, nameof(ConcurrencyToken))]
  bool UsesConcurrencyChecks { get; }

  /// <summary>
  /// The model for initializing instances of this entity.
  /// </summary>
  IInitializerModel Initializer { get; }

  /// <summary>
  /// The auto-generated column for this entity, if it exists.
  /// </summary>
  IAccessibleColumnModel? AutoGeneratedColumn { get; }

  /// <summary>
  /// The concurrency check column for this entity, if it exists.
  /// </summary>
  IAccessibleColumnModel? ConcurrencyToken { get; }

  /// <summary>
  /// The primary key for this entity.
  /// </summary>
  IPrimaryKeyModel PrimaryKey { get; }

  /// <summary>
  /// The columns for this entity.
  /// </summary>
  IReadOnlyCollection<IColumnModel> Columns { get; }

  /// <summary>
  /// The navigation properties for this entity.
  /// </summary>
  IReadOnlyCollection<INavigationModel> Navigations { get; }

  /// <summary>
  /// Tries to get the column with the specified name.
  /// </summary>
  /// <param name="name">The name of the column to get.</param>
  /// <param name="column">The column, if found, <c>null</c> otherwise.</param>
  /// <returns>True if the column was found, false otherwise.</returns>
  bool TryGetColumn(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleColumnModel? column);

  /// <summary>
  /// Tries to get the navigation with the specified name.
  /// </summary>
  /// <param name="name">The name of the navigation to get.</param>
  /// <param name="navigation">The navigation, if found, <c>null</c> otherwise.</param>
  /// <returns>True if the navigation was found, false otherwise.</returns>
  bool TryGetNavigation(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleNavigationModel? navigation);
}
