using CodeArchitects.Platform.CodeAnalysis;
using System.Diagnostics.CodeAnalysis;

namespace CodeArchitects.Platform.Data.AdoNet.Model;

[Experimental]
public interface IEntityModel
{
  string TableName { get; }
  
  Type Type { get; }

  IInitializerModel Initializer { get; }

  IColumnModel? AutoGeneratedColumn { get; }

  IPrimaryKeyModel PrimaryKey { get; }

  IReadOnlyList<IForeignKeyModel> ForeignKeys { get; }

  IReadOnlyList<IColumnModel> Columns { get; }
  
  IReadOnlyList<INavigationModel> Navigations { get; }

  bool TryGetNavigation(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleNavigationModel? navigation);
}
