using CodeArchitects.Platform.CodeAnalysis;
using System.Diagnostics.CodeAnalysis;

namespace CodeArchitects.Platform.Data.AdoNet.Model;

[Experimental]
public interface IEntityModel
{
  string Name { get; }

  string TableName { get; }
  
  Type Type { get; }

  IInitializerModel Initializer { get; }

  IAccessibleColumnModel? AutoGeneratedColumn { get; }

  IPrimaryKeyModel PrimaryKey { get; }

  IReadOnlyCollection<IForeignKeyModel> ForeignKeys { get; }

  IReadOnlyCollection<IColumnModel> Columns { get; }
  
  IReadOnlyCollection<INavigationModel> Navigations { get; }

  bool TryGetNavigation(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleNavigationModel? navigation);
}
