namespace CodeArchitects.Platform.Data.AdoNet.Model;

public interface IPrimaryKeyPropertyModel : IPropertyModel
{
  short KeyIndex { get; }
  
  bool IsAutoGenerated { get; }

  new Getter<object> Getter { get; }

  new Setter<object> Setter { get; }
}
