namespace CodeArchitects.Platform.Data.AdoNet.Model;

internal interface IPrimaryKeyModel
{
  bool IsComposite { get; }
  IPrimaryKeyPropertyModel? AutoGeneratedProperty { get; }
  Type Type { get; }
  IReadOnlyList<IPrimaryKeyPropertyModel> Properties { get; }
}
