using CodeArchitects.Platform.CodeAnalysis;

namespace CodeArchitects.Platform.Data.AdoNet.Model;

[Experimental]
public interface IPrimaryKeyPropertyModel : IPropertyModel, IAccessiblePropertyModel
{
  short PrimaryKeyIndex { get; }
  
  bool IsAutoGenerated { get; }
}
