using CodeArchitects.Platform.CodeAnalysis;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Model;

[Experimental]
public interface IPrimaryKeyModel
{
  [MemberNotNullWhen(true, nameof(TupleConstructor))]
  bool IsComposite { get; }

  IPrimaryKeyPropertyModel? AutoGeneratedProperty { get; }
  
  Type Type { get; }
  
  IReadOnlyList<IPrimaryKeyPropertyModel> Properties { get; }

  ConstructorInfo? TupleConstructor { get; } // TODO: This must be the constructor of Tuple, not ValueTuple
}
