// <auto-generated />
using System;
using EFCoreSample.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreSample.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221121142655_AddCart")]
    partial class AddCart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("CA:Multitenancy:TenantIdType", typeof(Guid))
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreSample.Domain.Model.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("EFCoreSample.Domain.Model.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("EFCoreSample.Domain.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasAnnotation("CA:Multitenancy:PropertyName", "TenantId");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9099eaf9-1e11-43f8-aebe-7dad26e53208"),
                            IsPublic = true,
                            Name = "iPhone",
                            Price = 1200.0m,
                            TenantId = new Guid("f2ae191d-8708-4ecb-9c53-f93b668a1744")
                        },
                        new
                        {
                            Id = new Guid("ec5f6fff-4def-4b93-b3f6-392fb4487d39"),
                            IsPublic = false,
                            Name = "iPad",
                            Price = 700.0m,
                            TenantId = new Guid("f2ae191d-8708-4ecb-9c53-f93b668a1744")
                        },
                        new
                        {
                            Id = new Guid("ab73d4b5-03c3-4fc4-8135-10773df6d757"),
                            IsPublic = false,
                            Name = "AirPods",
                            Price = 600.0m,
                            TenantId = new Guid("f2ae191d-8708-4ecb-9c53-f93b668a1744")
                        },
                        new
                        {
                            Id = new Guid("51e2887c-8442-48db-8e27-026638692b7e"),
                            IsPublic = true,
                            Name = "Dell Precision",
                            Price = 4000.0m,
                            TenantId = new Guid("26b27fd0-6507-42e1-9674-b777136d2256")
                        },
                        new
                        {
                            Id = new Guid("2fedacbf-bdd0-4083-8c98-8b97f6257663"),
                            IsPublic = false,
                            Name = "Dell XPS 15",
                            Price = 2300.0m,
                            TenantId = new Guid("26b27fd0-6507-42e1-9674-b777136d2256")
                        },
                        new
                        {
                            Id = new Guid("d9ee475d-eec4-4731-a638-37c4c36fca58"),
                            IsPublic = false,
                            Name = "Dell Monitor",
                            Price = 800.0m,
                            TenantId = new Guid("26b27fd0-6507-42e1-9674-b777136d2256")
                        });
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("EFCoreSample.Domain.Model.Order", b =>
                {
                    b.HasOne("EFCoreSample.Domain.Model.Cart", null)
                        .WithMany("Orders")
                        .HasForeignKey("CartId");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("EFCoreSample.Domain.Model.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreSample.Domain.Model.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCoreSample.Domain.Model.Cart", b =>
                {
                    b.Navigation("Orders")
                        .HasAnnotation("CA:AssociationKind", "<runtime annotation>");
                });
#pragma warning restore 612, 618
        }
    }
}
