using CodeArchitects.Platform.Data.AdoNet.Model;
using System.Diagnostics.CodeAnalysis;

namespace CodeArchitects.Platform.Data.AdoNet.Fixtures;

internal class MockEntityModel<TEntity, TKey> : IEntityModel<TEntity, TKey>
  where TEntity : class
  where TKey : IEquatable<TKey>
{
  private readonly IEntityModel _mock;

  public MockEntityModel(IEntityModel mock)
  {
    _mock = mock;
  }

  public string TableName => _mock.TableName;

  public string Name => _mock.Name;

  public Type Type => _mock.Type;

  public IPrimaryKeyModel PrimaryKey => _mock.PrimaryKey;

  public IReadOnlyCollection<IColumnModel> Columns => _mock.Columns;

  public IReadOnlyCollection<INavigationModel> Navigations => _mock.Navigations;

  public IInitializerModel Initializer => _mock.Initializer;

  public IReadOnlyCollection<IForeignKeyModel> ForeignKeys => _mock.ForeignKeys;

  public IColumnModel? AutoGeneratedColumn => _mock.AutoGeneratedColumn;

  IPrimaryKeyModel<TKey> IEntityModel<TEntity, TKey>.PrimaryKey => new MockPrimaryKeyModel<TKey>(PrimaryKey);

  public bool TryGetNavigation(ReadOnlySpan<char> name, [NotNullWhen(true)] out IAccessibleNavigationModel? navigationModel)
  {
    foreach (INavigationModel navigation in Navigations)
    {
      if (navigation is not IAccessibleNavigationModel accessibleNavigation)
        continue;

      if (accessibleNavigation.Member.Name == name.ToString())
      {
        navigationModel = accessibleNavigation;
        return true;
      }
    }

    navigationModel = null;
    return false;
  }
}

internal static class MockEntityModelExtensions
{
  public static IEntityModel<TEntity, TKey> Mocked<TEntity, TKey>(this IEntityModel mock)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    return new MockEntityModel<TEntity, TKey>(mock);
  }
}