using CodeArchitects.Platform.Data.AdoNet.Model;
using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Fixtures;

// TODO: Remove and use real model
internal class MockPrimaryKeyModel<TKey> : IPrimaryKeyModel<TKey>
  where TKey : IEquatable<TKey>
{
  private readonly IPrimaryKeyModel _mock;

  public MockPrimaryKeyModel(IPrimaryKeyModel mock)
  {
    _mock = mock;
  }

  public IAccessor<TKey> Accessor => new MockAccessor(_mock.Accessor);

  public bool IsComposite => _mock.IsComposite;

  public IPrimaryKeyPropertyModel? AutoGeneratedProperty => _mock.AutoGeneratedProperty;

  public Type Type => _mock.Type;

  public IReadOnlyList<IPrimaryKeyPropertyModel> Properties => _mock.Properties;

  public ConstructorInfo? TupleConstructor => _mock.TupleConstructor;

  IAccessor IPrimaryKeyModel.Accessor => _mock.Accessor;

  public object GetKeyComponent(TKey key, int index)
  {
    throw new NotImplementedException();
  }

  private class MockAccessor : IAccessor<TKey>
  {
    private readonly IAccessor _mock;

    public MockAccessor(IAccessor mock)
    {
      _mock = mock;
    }

    public TKey Get(object target)
    {
      return (TKey)_mock.Get(target)!;
    }

    public void Set(object target, TKey value)
    {
      _mock.Set(target, value);
    }
  }
}
