using CodeArchitects.Platform.Actors.Analyzer.Descriptors;
using Microsoft.CodeAnalysis;
using System.Text;

namespace CodeArchitects.Platform.Actors.Analyzer.Renderers;

internal readonly ref struct ActorFactoryRenderer
{
  private readonly SourceProductionContext _context;

  public ActorFactoryRenderer(SourceProductionContext context)
  {
    _context = context;
  }

  public void Render(ActorDescriptor descriptor)
  {
    StringBuilder source = new StringBuilder($$"""
      // <auto-generated />
      
      namespace {{descriptor.Namespace}}
      {
        /// <summary>
        /// Defines methods to create and initialize the <see cref="global::{{descriptor.Namespace}}.{{descriptor.ImplementationTypeName}}"/> actor.
        /// </summary>
        [global::CodeArchitects.Platform.Actors.ActorFactory(typeof(global::{{descriptor.Namespace}}.{{descriptor.ImplementationTypeName}}))]
        public interface I{{descriptor.ImplementationTypeName}}Factory
        {
          /// <summary>
          /// Retrieves an actor by its id.
          /// </summary>
          /// <param name="id">The unique identifier of the actor.</param>
          /// <returns>A proxy that can be used to invoke the actor.</returns>
          {{descriptor.InterfaceTypeFullName}} Get({{descriptor.IdTypeFullName}} id);

      """);

    if (!descriptor.IsVirtual)
    {
      source.Append("""

            /// <summary>
            /// Initializes a new actor with the provided id and initial state.
            /// </summary>
        """);

      if (!descriptor.GetsIdFromState)
      {
        source.Append("""/// <param name="id">The unique identifier of the actor.</param>""");
      }

      foreach (StateDependencyDescriptor dependency in descriptor.StateDependencies)
      {
        source.AppendLine();
        source.Append($"    /// <param name=\"{dependency.ParameterName}\">The '{dependency.ParameterName}' component of the actor state.</param>");
      }

      source.AppendLine();
      source.Append($$"""
          /// <returns>A proxy that can be used to invoke the actor.</returns>
          global::System.Threading.Tasks.Task<{{descriptor.InterfaceTypeFullName}}> CreateAsync(
      """);

      if (!descriptor.GetsIdFromState)
      {
        source.Append($"{descriptor.IdTypeFullName} id, ");
      }
      foreach (StateDependencyDescriptor dependency in descriptor.StateDependencies)
      {
        source.Append(dependency.TypeFullName);
        source.Append(' ');
        source.Append(dependency.ParameterName);
        source.Append(", ");
      }

      source.AppendLine("global::System.Threading.CancellationToken cancellationToken = default);");
    }

    source.AppendLine("""
          }
        }

        """);

    string text = source.ToString();
    _context.AddSource($"{descriptor.ImplementationTypeName}.g.cs", text);
  }
}
