parameters:
  - name: solution
    displayName: solution
    type: string
    default: "CodeArchitects.Platforform.sln"

steps:
- task: PowerShell@2
  displayName: "Run tests"
  inputs:
    targetType: 'inline'
    script: |
       # dotnet tool install --global dotnet-coverage
       # dotnet-coverage collect 'dotnet test ${{parameters.solution}} -m:1' -f xml  -o 'coverage.xml'
       dotnet test ${{parameters.solution}} --no-build