parameters:
  - name: condition
    type: string
  - name: nuGetConfigName
    type: string
steps:
- task: Powershell@2
  condition: ${{parameters.condition}}
  displayName: 'Run dotnet add source and publish'
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    targetType: 'inline'
    script: |
      # dotnet nuget add source $(SOURCE) -n $(SOURCE_NAME) -u $(SA) -p $(TOKEN) --store-password-in-clear-text --valid-authentication-types basic --configfile ${{parameters.nuGetConfigName}}
      dotnet nuget push ./nupkgs/*.nupkg -s "$(SOURCE)" -k "$(SA_TOKEN)"
