parameters:
  - name: solution
    displayName: solution
    type: string
    default: "*.sln"

steps:
- task: PowerShell@2
  displayName: "run tests & calculate code coverage"
  inputs:
    targetType: 'inline'
    script: |
     # dotnet tool install --global dotnet-coverage
     # dotnet-coverage collect 'dotnet test ${{parameters.solution}} -m:1' -f xml  -o 'coverage.xml'
     dotnet test ${{parameters.solution}} --no-restore --no-build