parameters:
  - name: solution
    displayName: solution
    type: string
    default: "*/**.sln"
  - name: nuGetConfigName
    displayName: nuGetConfigName
    type: string
    default: "NuGet.Config"

steps:
- task: DownloadSecureFile@1
  name: NuGetConfig
  inputs:
    secureFile: '${{parameters.nuGetConfigName}}'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Copy-Item -Path $("${{ parameters.nuGetConfigName }}.secureFilePath") -Destination ./NuGet.Config
  displayName: 'authentication'
- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages with dotnet cli
  inputs:
    command: 'restore'
    projects: '${{parameters.solution}}'
    feedsToUse: 'config'
    nugetConfigPath: '${{parameters.nuGetConfigName}}'
    noCache: true