parameters:
  - name: solution
    displayName: solution
    type: string
    default: "*.sln"
  - name: nuGetConfigName
    displayName: nuGetConfigName
    type: string
    default: "NuGet.Config"

steps:
- task: DownloadSecureFile@1
  name: securefile
  inputs:
    secureFile: '${{parameters.nuGetConfigName}}'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Copy-Item -Path $(securefile.secureFilePath) -Destination ./NuGet.Config
      dotnet nuget add source $(SOURCE) -n "$(SOURCE_NAME)" --force -u "$(SA_NAME)" -p "$(SA_TOKEN)" --store-password-in-clear-text --valid-authentication-types basic --configfile ./NuGet.Config
  displayName: 'authentication'
- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages with dotnet cli
  inputs:
    command: 'restore'
    projects: '${{parameters.solution}}'
    feedsToUse: 'config'
    nugetConfigPath: '${{parameters.nuGetConfigName}}'
    noCache: true