variables:
  NugetConfig: 'ca-esp7.Config'
  restoreTemplate: 'task/restore-nuget.yml'
  buildTemplate: 'task/dotnet-build.yml'
  testTemplate: 'task/dotnet-test.yml'
  packTemplate: 'task/dotnet-pack.yml'
  pushTemplate: 'task/dotnet-push.yml'
  check_pushTemplate: 'task/check-publish.yml'
  triggerCondition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  releaseCondition: or(eq('${{ parameters.Release }}', 'RC'), eq('${{ parameters.Release }}', 'Beta'))
  betaReleaseName: ${{ parameters.packageVersion }}-beta.${{ parameters.betaVersion }}
  prefix: 'CodeArchitects.Platform'
  ${{ if eq(parameters.release, 'beta') }}:
    pipelineVersion: ${{ variables.betaReleaseName }}
    condition: 'succeeded()'
  ${{ if ne(parameters.release, 'beta') }}:
    condition: and(${{variables.triggerCondition}}, ${{variables.releaseCondition}})
    pipelineVersion: ${{ parameters.packageVersion }}
