using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Builder;

internal abstract class EntityModelBuilder
{
  protected readonly List<MemberInfo> _keys;
  protected readonly HashSet<MemberInfo> _ignoredMembers;
  protected readonly Dictionary<MemberInfo, string> _columnNames;
  protected readonly List<AssociationBuilder> _associationBuilders;

  public EntityModelBuilder()
  {
    _keys = new();
    _ignoredMembers = new();
    _columnNames = new();
    _associationBuilders = new();
  }

  public void AddAssociation(AssociationBuilder builder)
  {
    _associationBuilders.Add(builder);
  }

  public abstract Type EntityType { get; }
  public IReadOnlyCollection<AssociationBuilder> Associations => _associationBuilders;
  public IReadOnlyCollection<MemberInfo> Keys => _keys;
  public IReadOnlyCollection<MemberInfo> IgnoredMembers => _ignoredMembers;
  public IReadOnlyDictionary<MemberInfo, string> ColumnNames => _columnNames;
  public MemberInfo? AutoGeneratedColumn { get; protected set; }
  public string? AutoGeneratedColumnName { get; protected set; }
  public string? TableName { get; protected set; }
}
