using CodeArchitects.Platform.Common.Utils;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;
using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Builder;

internal class EntityModelBuilder<TEntity> : EntityModelBuilder, IEntityModelBuilder<TEntity>
  where TEntity : class
{
  public override Type EntityType => typeof(TEntity);

  public IEntityModelBuilder<TEntity> Ignore(string memberName)
  {
    if (!FindMemberAndType(memberName, out MemberInfo? member, out _, out Func<string, ArgumentException>? exceptionFactory))
      throw exceptionFactory(nameof(memberName));

    _ignoredMembers.Add(member);
    return this;
  }

  public IEntityModelBuilder<TEntity> Ignore<TProperty>(Expression<Func<TEntity, TProperty>> expression)
  {
    if (expression.Body is not MemberExpression memberExpression || !TryGetPropertyOrField(memberExpression, out MemberInfo? member))
      throw new ArgumentException("The expression must be 'x => x.Member'.", nameof(expression));

    AutoGeneratedColumn = member;
    return this;
  }

  public IEntityModelBuilder<TEntity> WithAutoGeneratedColumn(string columnName)
  {
    AutoGeneratedColumnName = columnName;
    return this;
  }

  public IEntityModelBuilder<TEntity> WithAutoGeneratedColumn<TProperty>(Expression<Func<TEntity, TProperty>> expression)
  {
    if (expression.Body is not MemberExpression memberExpression || !TryGetPropertyOrField(memberExpression, out MemberInfo? member))
      throw new ArgumentException("The expression must be 'x => x.Member'.", nameof(expression));

    _ignoredMembers.Add(member);
    return this;
  }

  public IEntityModelBuilder<TEntity> WithColumnName<TProperty>(Expression<Func<TEntity, TProperty>> expression, string columnName)
  {
    if (expression.Body is not MemberExpression memberExpression || !TryGetPropertyOrField(memberExpression, out MemberInfo? member))
      throw new ArgumentException("The expression must be 'x => x.Member'.", nameof(expression));

    _columnNames[member] = columnName;
    return this;
  }

  public IEntityModelBuilder<TEntity> WithColumnName<TProperty>(string memberName, string columnName)
  {
    if (!FindMemberAndType(memberName, out MemberInfo? member, out _, out Func<string, ArgumentException>? exceptionFactory))
      throw exceptionFactory(nameof(memberName));

    _columnNames[member] = columnName;
    return this;
  }

  public IEntityModelBuilder<TEntity> WithKey(params string[] keyNames)
  {
    _keys.Clear();

    foreach (string keyName in keyNames)
    {
      if (!FindMemberAndType(keyName, out MemberInfo? member, out Type? memberType, out Func<string, ArgumentException>? exceptionFactory))
        throw exceptionFactory(nameof(keyNames));

      if (!CheckIEquatable(member, memberType, out exceptionFactory))
        throw exceptionFactory(nameof(keyNames));

      _keys.Add(member);
    }

    return this;
  }

  public IEntityModelBuilder<TEntity> WithKey<TKey>(Expression<Func<TEntity, TKey>> expression)
  {
    MemberInfo? member;
    switch (expression.Body)
    {
      case MemberExpression memberExpression:
        if (!TryGetPropertyOrField(memberExpression, out member))
          throw InvalidExpression();

        _keys.Clear();
        _keys.Add(member);
        return this;

      case NewExpression newExpression:
        if (!newExpression.Type.IsAnonymousType())
          throw InvalidExpression();

        _keys.Clear();
        foreach (Expression argument in newExpression.Arguments)
        {
          if (argument is not MemberExpression memberExpression || !TryGetPropertyOrField(memberExpression, out member))
            throw InvalidExpression();

          _keys.Add(member);
        }
        return this;

      default:
        throw InvalidExpression();
    }

    static ArgumentException InvalidExpression() => new ArgumentException("The expression must be 'x => x.Key' for simple keys or 'x => new { x.Key1, ..., x.KeyN }' for composite keys.", nameof(expression));
  }

  public IEntityModelBuilder<TEntity> WithTableName(string tableName)
  {
    TableName = tableName;
    return this;
  }

  private static bool TryGetPropertyOrField(MemberExpression expression, [NotNullWhen(true)] out MemberInfo? member)
  {
    if (expression.Expression is ParameterExpression && expression.Member is PropertyInfo or FieldInfo)
    {
      member = expression.Member;
      return true;
    }

    member = null;
    return false;
  }

  private static bool CheckIEquatable(
    MemberInfo member,
    Type memberType,
    [NotNullWhen(false)] out Func<string, ArgumentException>? exceptionFactory)
  {
    if (typeof(IEquatable<>).MakeGenericType(memberType).IsAssignableFrom(memberType))
    {
      exceptionFactory = paramName => new ArgumentException($"Key member '{member.Name}' does not implement the IEquatable interface.", paramName);
      return false;
    }

    exceptionFactory = null;
    return true;
  }

  private static bool FindMemberAndType(
    string memberName,
    [NotNullWhen(true)] out MemberInfo? member,
    [NotNullWhen(true)] out Type? memberType,
    [NotNullWhen(false)] out Func<string, ArgumentException>? exceptionFactory)
  {
    MemberInfo[] members = typeof(TEntity).GetMember(
      name: memberName,
      type: MemberTypes.Field | MemberTypes.Property,
      bindingAttr: BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);

    if (members.Length == 0)
    {
      member = null;
      memberType = null;
      exceptionFactory = paramName => new ArgumentException($"Could not find a property or a field named '{memberName}'.", paramName);
    }
    if (members.Length > 1)
    {
      member = null;
      memberType = null;
      exceptionFactory = paramName => new ArgumentException($"Ambiguous member name '{memberName}'.", paramName);
    }

    switch (members[0])
    {
      case PropertyInfo property:
        member = property;
        memberType = property.PropertyType;
        exceptionFactory = null;
        return true;
      case FieldInfo field:
        member = field;
        memberType = field.FieldType;
        exceptionFactory = null;
        return true;
      default:
        throw Errors.Unreacheable;
    }
  }
}
