using CodeArchitects.Platform.Data.AdoNet.Model.Implementation;
using System.Diagnostics;
using System.Linq.Expressions;
using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Builder;

internal class EntityModelBuilder<TEntity> : EntityModelBuilder, IEntityModelBuilder<TEntity>
  where TEntity : class
{
  private readonly List<string> _keyNames;
  private readonly HashSet<MemberInfo> _ignoredMembers;
  private readonly Dictionary<MemberInfo, string> _columnNames;
  private MemberInfo? _autoGeneratedColumn;
  private string? _tableName;
  private bool _hasCompleted;

  public EntityModelBuilder(string entityName)
    : base(entityName)
  {
    _keyNames = new();
    _ignoredMembers = new();
    _columnNames = new();
  }

  public override Type EntityType => typeof(TEntity);

  public IEntityModelBuilder<TEntity> Ignore(string memberName)
  {
    MemberInfo member = GetMember(EntityType, memberName);

    _ignoredMembers.Add(member);
    return this;
  }

  public IEntityModelBuilder<TEntity> Ignore<TProperty>(Expression<Func<TEntity, TProperty>> expression)
  {
    if (!TryGetPropertyOrField(expression.Body, out _autoGeneratedColumn))
      throw new ModelConfigurationException("The expression must be 'x => x.Member'.");

    return this;
  }

  public IEntityModelBuilder<TEntity> WithAutoGeneratedColumn(string memberName)
  {
    _autoGeneratedColumn = GetMember(EntityType, memberName);

    return this;
  }

  public IEntityModelBuilder<TEntity> WithAutoGeneratedColumn<TProperty>(Expression<Func<TEntity, TProperty>> expression)
  {
    if (!TryGetPropertyOrField(expression.Body, out MemberInfo? member))
      throw new ModelConfigurationException("The expression must be 'x => x.Member'.");

    _ignoredMembers.Add(member);

    return this;
  }

  public IEntityModelBuilder<TEntity> WithColumnName<TProperty>(Expression<Func<TEntity, TProperty>> expression, string columnName)
  {
    if (!TryGetPropertyOrField(expression.Body, out MemberInfo? member))
      throw new ModelConfigurationException("The expression must be 'x => x.Member'.");

    _columnNames[member] = columnName;

    return this;
  }

  public IEntityModelBuilder<TEntity> WithColumnName<TProperty>(string memberName, string columnName)
  {
    MemberInfo member = GetMember(EntityType, memberName);
    _columnNames[member] = columnName;

    return this;
  }

  public IEntityModelBuilder<TEntity> WithKey(params string[] keyNames)
  {
    CheckKeyArity(keyNames.Length);

    _keyNames.Clear();

    foreach (string keyName in keyNames)
    {
      (MemberInfo member, Type memberType) = GetMemberAndType(EntityType, keyName);
      CheckIEquatable(member, memberType);

      _keyNames.Add(keyName);
    }

    return this;
  }

  public IEntityModelBuilder<TEntity> WithKey<TKey>(Expression<Func<TEntity, TKey>> expression)
  {
    _keyNames.Clear();

    IEnumerable<string> keyNames = GetKeyNames(expression.Body)
      .Select(name => name.IsColumnName
        ? throw new ModelConfigurationException($"'{nameof(ModelConfiguration)}.{nameof(ModelConfiguration.Column)}' is not supported for primary keys.")
        : name.Value);

    _keyNames.AddRange(keyNames);

    return this;
  }

  public IEntityModelBuilder<TEntity> WithTableName(string tableName)
  {
    _tableName = tableName;

    return this;
  }

  public override EntityModel Build()
  {
    Debug.Assert(!_hasCompleted, "Builder had already completed.");
    _hasCompleted = true;

    IReadOnlyList<(MemberInfo, Type)> keyMembersAndTypes = GetKeyMembersAndTypes();

    InitializerModel initializerModel = InitializerModel.Create(EntityType);
    PrimaryKeyModel primaryKeyModel = PrimaryKeyModel.Create(keyMembersAndTypes);

    return EntityModel.Create(EntityType, initializerModel, primaryKeyModel);
  }

  private IReadOnlyList<(MemberInfo, Type)> GetKeyMembersAndTypes()
  {
    if (_keyNames.Count != 0)
    {
      return _keyNames
        .Select(name => GetMemberAndType(EntityType, name))
        .ToList();
    }

    try
    {
      (MemberInfo, Type) memberAndType = GetMemberAndType(EntityType, "Id");
      return new[] { memberAndType };
    }
    catch (ModelConfigurationException)
    {
      throw new ModelConfigurationException($"Could not find a default key for entity of type '{EntityType}'");
    }
  }

  private static void CheckIEquatable(MemberInfo member, Type memberType)
  {
    if (!typeof(IEquatable<>).MakeGenericType(memberType).IsAssignableFrom(memberType))
      throw new ModelConfigurationException($"Key member '{member.Name}' does not implement the IEquatable interface.");
  }
}
