using CodeArchitects.Platform.Data.AdoNet.Model.Implementation;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;
using System.Reflection;
using System.Reflection.Metadata;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Builder;

internal class EntityModelBuilder<TEntity> : EntityModelBuilder, IEntityModelBuilder<TEntity>
  where TEntity : class
{
  private readonly List<Name> _keyNames;
  private readonly HashSet<MemberInfo> _ignoredMembers;
  private readonly Dictionary<MemberInfo, string> _columnNames;
  private MemberInfo? _autoGeneratedColumn;
  private string? _tableName;
  private IReadOnlyCollection<Type>? _entityTypes;
  private HashSet<Association> _associationsFrom;
  private HashSet<Association> _associationsTo;

  public EntityModelBuilder(string entityName)
    : base(entityName)
  {
    _keyNames = new();
    _ignoredMembers = new();
    _columnNames = new();
    _associationsFrom = new(AssociationEqualityComparer.Instance);
    _associationsTo = new(AssociationEqualityComparer.Instance);
  }

  public override Type EntityType => typeof(TEntity);

  [MemberNotNullWhen(true, nameof(_entityTypes))]
  private bool HasCompleted { get; set; }

  public IEntityModelBuilder<TEntity> Ignore(string memberName)
  {
    MemberInfo member = GetMember(typeof(TEntity), memberName);

    _ignoredMembers.Add(member);
    return this;
  }

  public IEntityModelBuilder<TEntity> Ignore<TProperty>(Expression<Func<TEntity, TProperty>> expression)
  {
    if (!TryGetPropertyOrField(expression.Body, out _autoGeneratedColumn))
      throw new ModelConfigurationException("The expression must be 'x => x.Member'.");

    return this;
  }

  public IEntityModelBuilder<TEntity> WithAutoGeneratedColumn(string memberName)
  {
    _autoGeneratedColumn = GetMember(typeof(TEntity), memberName);

    return this;
  }

  public IEntityModelBuilder<TEntity> WithAutoGeneratedColumn<TProperty>(Expression<Func<TEntity, TProperty>> expression)
  {
    if (!TryGetPropertyOrField(expression.Body, out MemberInfo? member))
      throw new ModelConfigurationException("The expression must be 'x => x.Member'.");

    _ignoredMembers.Add(member);

    return this;
  }

  public IEntityModelBuilder<TEntity> WithColumnName<TProperty>(Expression<Func<TEntity, TProperty>> expression, string columnName)
  {
    if (!TryGetPropertyOrField(expression.Body, out MemberInfo? member))
      throw new ModelConfigurationException("The expression must be 'x => x.Member'.");

    _columnNames[member] = columnName;

    return this;
  }

  public IEntityModelBuilder<TEntity> WithColumnName<TProperty>(string memberName, string columnName)
  {
    MemberInfo member = GetMember(typeof(TEntity), memberName);
    _columnNames[member] = columnName;

    return this;
  }

  public IEntityModelBuilder<TEntity> WithKey(params string[] keyNames)
  {
    _keyNames.Clear();

    foreach (string keyName in keyNames)
    {
      (MemberInfo member, Type memberType) = GetMemberAndType(typeof(TEntity), keyName);
      CheckIEquatable(member, memberType);

      _keyNames.Add(keyName);
    }

    return this;
  }

  public IEntityModelBuilder<TEntity> WithKey(params Name[] keyNames)
  {
    _keyNames.Clear();

    foreach (Name keyName in keyNames)
    {
      if (!keyName.IsColumnName)
      {
        (MemberInfo member, Type memberType) = GetMemberAndType(typeof(TEntity), keyName.Value);
        CheckIEquatable(member, memberType);
      }

      _keyNames.Add(keyName);
    }

    return this;
  }

  public IEntityModelBuilder<TEntity> WithKey<TKey>(Expression<Func<TEntity, TKey>> expression)
  {
    _keyNames.Clear();
    _keyNames.AddRange(GetKeyNames(expression.Body));

    return this;
  }

  public IEntityModelBuilder<TEntity> WithTableName(string tableName)
  {
    _tableName = tableName;

    return this;
  }

  public override void Complete(IReadOnlyCollection<Type> entityTypes, IEnumerable<Association> associations)
  {
    Debug.Assert(!HasCompleted, "Builder had already completed.");

    HasCompleted = true;
    _entityTypes = entityTypes;

    foreach (Association association in associations)
    {
      if (association.From == EntityType)
      {
        _associationsFrom.Add(association);
      }

      if (association.To == EntityType)
      {
        _associationsTo.Add(association);
      }
    }
  }

  public override IEntityModel Build()
  {
    MemberInfo[] members = EntityType.GetMembers(BindingFlags.Instance | BindingFlags.Public);

    IReadOnlyList<AccessibleMemberComponent> memberComponents = members
      .Where(member => !_ignoredMembers.Contains(member))
      .Select(AccessibleMemberComponent.Create)
      .ToList();

    IReadOnlyDictionary<MemberInfo, DirectAssociation> foreignKeyMembers = _associationsTo
      .OfType<DirectAssociation>()
      .SelectMany(association => association.ForeignKeyNames
        .Where(name => !name.IsColumnName)
        .Select(name => (name, association)))
      .ToDictionary(pair => GetMember(typeof(TEntity), pair.name.Value), pair => pair.association);

    IReadOnlyCollection<MemberInfo> keyMembers = GetKeyMembers(members);

    List<AccessibleColumnModel> accessibleColumns = new();

    foreach (AccessibleMemberComponent memberComponent in memberComponents)
    {
      if (!ModelConfiguration.IsSupportedColumnType(memberComponent.Type))
      {
        // This could be a navigation
      }
      else
      {
        AccessibleColumnModel column = ProcessColumnMemberComponent(memberComponent, keyMembers, foreignKeyMembers);
        accessibleColumns.Add(column);
      }
    }
  }

  private AccessibleColumnModel ProcessColumnMemberComponent(
    AccessibleMemberComponent memberComponent,
    IReadOnlyCollection<MemberInfo> keyMembers,
    IReadOnlyDictionary<MemberInfo, DirectAssociation> foreignKeyMembers)
  {
    bool isForeignKey = foreignKeyMembers.TryGetValue(memberComponent.Member, out DirectAssociation? association);
    bool isPrimaryKey = keyMembers.Contains(memberComponent.Member);

    if (isForeignKey && isPrimaryKey)
    {

    }
    else if (isPrimaryKey)
    {

    }
    else if (isForeignKey)
    {

    }
    else
    {

    }
  }

  private IReadOnlyCollection<MemberInfo> GetKeyMembers(IEnumerable<MemberInfo> members)
  {
    if (_keyNames.Count != 0)
    {
      return _keyNames
        .Select(name => GetMember(typeof(TEntity), name.Value))
        .ToHashSet();
    }

    MemberInfo? id = members.SingleOrDefault(member => member.Name == "Id");
    if (id is null)
      throw new ModelConfigurationException($"Could not infer the key columns for entity of type '{typeof(TEntity).Name}'.");

    return new[] { id };
  }

  private static void CheckIEquatable(MemberInfo member, Type memberType)
  {
    if (!typeof(IEquatable<>).MakeGenericType(memberType).IsAssignableFrom(memberType))
      throw new ModelConfigurationException($"Key member '{member.Name}' does not implement the IEquatable interface.");
  }
}
