using System.Linq.Expressions;
using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Builder;

public class EntityModelBuilder<TEntity>
  where TEntity : class
{
  private List<MemberInfo> _keys = new();
  private MemberInfo? _autoGeneratedColumn;
  private string? _tableName;

  public EntityModelBuilder<TEntity> WithKey<TKey>(Expression<Func<TEntity, TKey>> expression)
  {
    return this;
  }

  public EntityModelBuilder<TEntity> WithKey(params string[] keyNames)
  {
    return this;
  }

  public EntityModelBuilder<TEntity> WithAutoGeneratedColumn<TProperty>(Expression<Func<TEntity, TProperty>> expression)
  {
    return this;
  }

  public EntityModelBuilder<TEntity> WithAutoGeneratedColumn(string name)
  {
    return this;
  }

  public EntityModelBuilder<TEntity> WithTableName(string name)
  {
    return this;
  }

  public EntityModelBuilder<TEntity> Ignore<TProperty>(Expression<Func<TEntity, TProperty>> expression)
  {
    return this;
  }

  public EntityModelBuilder<TEntity> Ignore(string propertyName)
  {
    return this;
  }

  public EntityModelBuilder<TEntity> WithAggregation<TNavigation>(Expression<Func<TEntity, TNavigation>> expression, Action<NavigationModelBuilder<TEntity, TNavigation>> buildAction)
    where TNavigation : class
  {
    return this;
  }

  public EntityModelBuilder<TEntity> WithComposition<TNavigation>(Expression<Func<TEntity, TNavigation>> expression, Action<NavigationModelBuilder<TEntity, TNavigation>> buildAction)
    where TNavigation : class
  {
    return this;
  }
}
