using System.Linq.Expressions;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Builder;

public interface IEntityModelBuilder<TEntity>
  where TEntity : class
{
  IEntityModelBuilder<TEntity> WithKey(params string[] keyNames);

  IEntityModelBuilder<TEntity> WithKey<TKey>(Expression<Func<TEntity, TKey>> expression);

  IEntityModelBuilder<TEntity> WithAutoGeneratedColumn(string columnName);

  IEntityModelBuilder<TEntity> WithAutoGeneratedColumn<TProperty>(Expression<Func<TEntity, TProperty>> expression);

  IEntityModelBuilder<TEntity> Ignore(string memberName);
  
  IEntityModelBuilder<TEntity> Ignore<TProperty>(Expression<Func<TEntity, TProperty>> expression);
  
  IEntityModelBuilder<TEntity> WithTableName(string tableName);

  IEntityModelBuilder<TEntity> WithColumnName<TProperty>(Expression<Func<TEntity, TProperty>> expression, string columnName);

  IEntityModelBuilder<TEntity> WithColumnName<TProperty>(string memberName, string columnName);
}