using System.Linq.Expressions;

namespace CodeArchitects.Platform.Data.AdoNet.Model.Builder;

/// <summary>
/// A builder that can be used to configure an entity type.
/// </summary>
/// <typeparam name="TEntity">The entity type.</typeparam>
public interface IEntityModelBuilder<TEntity>
  where TEntity : class
{
  /// <summary>
  /// Specifies the primary key property or properties of the navigation.
  /// </summary>
  /// <remarks>
  /// If the primary key is a simple key, then a member expression can be used: <c>entity => entity.PrimaryKey</c>.
  /// A composite primary key can be specified by using an anonymous object creation: <c>entity => new { entity.PrimaryKey1, entity.PrimaryKey2 }</c>.
  /// </remarks>
  /// <typeparam name="TKey">The primary key type.</typeparam>
  /// <param name="expression">An expression that represents the path to the primary key.</param>
  /// <returns>The same <see cref="IEntityModelBuilder{TEntity}"/> that can be used to further configure the entity.</returns>
  IEntityModelBuilder<TEntity> WithKey<TKey>(Expression<Func<TEntity, TKey>> expression);

  /// <summary>
  /// Specifies the primary key property or properties of the navigation.
  /// </summary>
  /// <param name="keyNames">The names of the primary key properties.</param>
  /// <returns>The same <see cref="IEntityModelBuilder{TEntity}"/> that can be used to further configure the entity.</returns>
  IEntityModelBuilder<TEntity> WithKey(params string[] keyNames);

  /// <summary>
  /// Specifies that a member of the class is mapped to a column whose value is autogenerated by the database on insertion.
  /// </summary>
  /// <typeparam name="TMember">The member type.</typeparam>
  /// <param name="expression">An expression that represents the path to the member.</param>
  /// <returns>The same <see cref="IEntityModelBuilder{TEntity}"/> that can be used to further configure the entity.</returns>
  IEntityModelBuilder<TEntity> WithAutoGeneratedColumn<TMember>(Expression<Func<TEntity, TMember>> expression);

  /// <summary>
  /// Specifies that a member of the class is mapped to a column whose value is autogenerated by the database on insertion.
  /// </summary>
  /// <param name="memberName">The name of the member.</param>
  /// <returns>The same <see cref="IEntityModelBuilder{TEntity}"/> that can be used to further configure the entity.</returns>
  IEntityModelBuilder<TEntity> WithAutoGeneratedColumn(string memberName);

  /// <summary>
  /// Specifies that a member of the class is not mapped to any column.
  /// </summary>
  /// <typeparam name="TMember">The member type.</typeparam>
  /// <param name="expression">An expression that represents the path to the member.</param>
  /// <returns>The same <see cref="IEntityModelBuilder{TEntity}"/> that can be used to further configure the entity.</returns>
  IEntityModelBuilder<TEntity> Ignore<TMember>(Expression<Func<TEntity, TMember>> expression);

  /// <summary>
  /// Specifies that a member of the class is not mapped to any column.
  /// </summary>
  /// <param name="memberName">The name of the member</param>
  /// <returns>The same <see cref="IEntityModelBuilder{TEntity}"/> that can be used to further configure the entity.</returns>
  IEntityModelBuilder<TEntity> Ignore(string memberName);

  /// <summary>
  /// Specifies the name of the table this entity is mapped to.
  /// </summary>
  /// <param name="tableName">The name of the table.</param>
  /// <returns>The same <see cref="IEntityModelBuilder{TEntity}"/> that can be used to further configure the entity.</returns>
  IEntityModelBuilder<TEntity> WithTableName(string tableName);

  /// <summary>
  /// Specifies the name of the column the specified member is mapped to.
  /// </summary>
  /// <typeparam name="TMember">The member type.</typeparam>
  /// <param name="expression">An expression that represents the path to the member.</param>
  /// <param name="columnName">The name of the column.</param>
  /// <returns>The same <see cref="IEntityModelBuilder{TEntity}"/> that can be used to further configure the entity.</returns>
  IEntityModelBuilder<TEntity> WithColumnName<TMember>(Expression<Func<TEntity, TMember>> expression, string columnName);

  /// <summary>
  /// Specifies the name of the column the specified member is mapped to.
  /// </summary>
  /// <param name="memberName">The name of the member</param>
  /// <param name="columnName">The name of the column.</param>
  /// <returns>The same <see cref="IEntityModelBuilder{TEntity}"/> that can be used to further configure the entity.</returns>
  IEntityModelBuilder<TEntity> WithColumnName(string memberName, string columnName);
}