using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Model.FluentMock;
using System.Collections;
using System.Data.Common;
using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Fixtures.Models;

internal static class WithNavigationOnParent
{
  public class Parent
  {
    public Guid Id { get; set; } // 0
    public string? Name { get; set; } // 1

    public ChildA? ChildA { get; set; }
    public IList<ChildB>? ChildrenB { get; set; }
  }

  public class ChildA
  {
    public Guid Id { get; set; } // 2
    public string? Name { get; set; } // 3
    public Guid ParentId { get; set; } // 4
  }

  public class ChildB
  {
    public int Id { get; set; } // 5
    public string? Name { get; set; } // 6
    public Guid ParentId { get; set; } // 7
  }

  public static readonly IEntityModel ParentModel = CreateParentModel();
  public static readonly IEntityModel ChildAModel = CreateChildAModel();
  public static readonly IEntityModel ChildBModel = CreateChildBModel();

  private static IEntityModel CreateParentModel()
  {
    IStandardPrimaryKeyColumnModel idProperty = PrimaryKeyColumnModelBuilder.Build(_ => _
      .SetIndex(0)
      .SetType(typeof(Guid))
      .SetIsAutoGenerated(false)
      .SetHasMember(true)
      .SetProperty(typeof(Parent).GetRequiredProperty(nameof(Parent.Id))));

    IOrdinaryColumnModel nameProperty = OrdinaryColumnModelBuilder.Build(_ => _
      .SetIndex(1)
      .SetType(typeof(string))
      .SetHasMember(true)
      .SetProperty(typeof(Parent).GetRequiredProperty(nameof(Parent.Name))));

    INavigationModel childANavigation = SimpleAccessibleNavigationModelBuilder.Build(_ => _
      .SetId(1)
      .SetType(typeof(ChildA))
      .SetIsOnDependent(true)
      .SetIsCollection(false)
      .SetHasMember(true)
      .SetProperty(typeof(Parent).GetRequiredProperty(nameof(Parent.ChildA)))
      .SetTo(_ => _
        .SetType(typeof(ChildA))
        .SetPrimaryKey(_ => _
          .SetType(typeof(Guid)))));

    INavigationModel childrenBNavigation = SimpleAccessibleNavigationModelBuilder.Build(_ => _
      .SetId(2)
      .SetType(typeof(ICollection<ChildB>))
      .SetIsOnDependent(true)
      .SetIsCollection(true)
      .SetHasMember(true)
      .SetProperty(typeof(Parent).GetRequiredProperty(nameof(Parent.ChildrenB)))
      .SetTo(_ => _
        .SetType(typeof(ChildB))
        .SetPrimaryKey(_ => _
          .SetType(typeof(int)))));

    return EntityModelBuilder.Build(_ => _
      .SetType(typeof(Parent))
      .SetPrimaryKey(_ => _
        .SetIsComposite(false)
        .SetType(typeof(Guid))
        .SetColumns(idProperty))
      .SetColumns(idProperty, nameProperty)
      .SetInitializer(_ => _
        .SetConstructor(typeof(Parent).GetRequiredConstructor())
        .SetConstructorProperties()
        .SetInitializerProperties(idProperty, nameProperty))
      .SetNavigations(childANavigation, childrenBNavigation));
  }

  private static IEntityModel CreateChildAModel()
  {
    IStandardPrimaryKeyColumnModel idProperty = PrimaryKeyColumnModelBuilder.Build(_ => _
      .SetIndex(0)
      .SetType(typeof(Guid))
      .SetIsAutoGenerated(false)
      .SetHasMember(true)
      .SetProperty(typeof(ChildA).GetRequiredProperty(nameof(ChildA.Id))));

    IOrdinaryColumnModel nameProperty = OrdinaryColumnModelBuilder.Build(_ => _
      .SetIndex(1)
      .SetType(typeof(string))
      .SetHasMember(true)
      .SetProperty(typeof(ChildA).GetRequiredProperty(nameof(ChildA.Name))));

    INavigationModel parentNavigation = SimpleAccessibleNavigationModelBuilder.Build(_ => _
      .SetId(1)
      .SetType(typeof(Parent))
      .SetIsOnDependent(false)
      .SetIsCollection(false)
      .SetHasMember(false)
      .SetProperty(null!)
      .SetTo(_ => _
        .SetType(typeof(Parent))
        .SetPrimaryKey(_ => _
          .SetType(typeof(Guid)))));

    IOrdinaryColumnModel parentIdProperty = OrdinaryColumnModelBuilder.Build(_ => _
      .SetIndex(2)
      .SetType(typeof(Guid))
      .SetHasMember(true)
      .SetProperty(typeof(ChildA).GetRequiredProperty(nameof(ChildA.ParentId))));

    return EntityModelBuilder.Build(_ => _
      .SetType(typeof(ChildA))
      .SetPrimaryKey(_ => _
        .SetIsComposite(false)
        .SetType(typeof(Guid))
        .SetColumns(idProperty))
      .SetColumns(idProperty, nameProperty, parentIdProperty)
      .SetInitializer(_ => _
        .SetConstructor(typeof(ChildA).GetRequiredConstructor())
        .SetConstructorProperties()
        .SetInitializerProperties(idProperty, nameProperty, parentIdProperty))
      .SetNavigations(parentNavigation));
  }

  public static IEntityModel CreateChildBModel()
  {
    IStandardPrimaryKeyColumnModel idProperty = PrimaryKeyColumnModelBuilder.Build(_ => _
      .SetIndex(0)
      .SetType(typeof(int))
      .SetIsAutoGenerated(true)
      .SetHasMember(true)
      .SetProperty(typeof(ChildB).GetRequiredProperty(nameof(ChildB.Id))));

    IOrdinaryColumnModel nameProperty = OrdinaryColumnModelBuilder.Build(_ => _
      .SetIndex(1)
      .SetType(typeof(string))
      .SetHasMember(true)
      .SetProperty(typeof(ChildB).GetRequiredProperty(nameof(ChildB.Name))));

    INavigationModel parentNavigation = SimpleAccessibleNavigationModelBuilder.Build(_ => _
      .SetId(2)
      .SetType(typeof(Parent))
      .SetIsOnDependent(false)
      .SetIsCollection(true)
      .SetHasMember(false)
      .SetProperty(null)
      .SetTo(_ => _
        .SetType(typeof(Parent))
        .SetPrimaryKey(_ => _
          .SetType(typeof(Guid)))));

    IOrdinaryColumnModel parentIdProperty = OrdinaryColumnModelBuilder.Build(_ => _
      .SetIndex(2)
      .SetType(typeof(Guid))
      .SetHasMember(true)
      .SetProperty(typeof(ChildB).GetRequiredProperty(nameof(ChildB.ParentId)))
      /*.SetNavigation(parentNavigation)*/);

    return EntityModelBuilder.Build(_ => _
      .SetType(typeof(ChildB))
      .SetPrimaryKey(_ => _
        .SetIsComposite(false)
        .SetType(typeof(int))
        .SetColumns(idProperty))
      .SetColumns(idProperty, nameProperty, parentIdProperty)
      .SetInitializer(_ => _
        .SetConstructor(typeof(ChildB).GetRequiredConstructor())
        .SetConstructorProperties()
        .SetInitializerProperties(idProperty, nameProperty, parentIdProperty))
      .SetNavigations(parentNavigation));
  }

  public class ChildBEqualityComparer : IEqualityComparer<ChildB>
  {
    bool IEqualityComparer<ChildB>.Equals(ChildB? x, ChildB? y)
    {
      if (x is null)
        return y is null;

      if (y is null)
        return false;

      return x.Id == y.Id;
    }

    int IEqualityComparer<ChildB>.GetHashCode(ChildB obj)
    {
      return obj.Id.GetHashCode();
    }
  }
}
