using Bogus;
using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Model.FluentMock;
using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Fixtures.Models;

internal static class WithDifferentPrimaryKeys
{
  public class SimpleEntity
  {
    public int Id { get; set; }
    public string? Name { get; set; }

    private static readonly Faker<SimpleEntity> s_faker = new Faker<SimpleEntity>()
      .RuleFor(entity => entity.Id, faker => faker.UniqueIndex)
      .RuleFor(entity => entity.Name, faker => faker.Name.FullName());

    public static SimpleEntity One() => s_faker.Generate();
  }

  public class CompositeEntity
  {
    public Guid Id1 { get; set; }
    public int Id2 { get; set; }
    public string? Name { get; set; }

    private static readonly Faker<CompositeEntity> s_faker = new Faker<CompositeEntity>()
      .RuleFor(entity => entity.Id1, Guid.NewGuid)
      .RuleFor(entity => entity.Id2, faker => faker.UniqueIndex)
      .RuleFor(entity => entity.Name, faker => faker.Name.FullName());

    public static CompositeEntity One() => s_faker.Generate();
  }

  public static IEntityModel<SimpleEntity, int> CreateSimpleEntityModel(bool autoGeneratedId)
  {
    EntityTypeDelegator entityType = new EntityTypeDelegator(typeof(SimpleEntity), autoGeneratedId);

    PropertyInfo idPropertyInfo = typeof(SimpleEntity).GetRequiredProperty(nameof(SimpleEntity.Id));
    PropertyInfo namePropertyInfo = typeof(SimpleEntity).GetRequiredProperty(nameof(SimpleEntity.Name));

    IPrimaryKeyColumnModel idProperty = PrimaryKeyColumnModelBuilder.Build(_ => _
      .SetType(typeof(int))
      .SetIndex(0)
      .SetIsAutoGenerated(autoGeneratedId)
      .SetHasMember(true)
      .SetProperty(idPropertyInfo)
      .SetIsPrimaryKey(true)
      .Setup(mock => mock
        .Setup(x => x.Member)
        .Returns(idPropertyInfo))
      .Setup(mock => mock
        .Setup(x => x.GetValue)
        .Returns(idPropertyInfo.GetValue)))
      .Mocked();

    IOrdinaryColumnModel nameProperty = OrdinaryColumnModelBuilder.Build(_ => _
      .SetType(typeof(string))
      .SetIndex(1)
      .SetIsAutoGenerated(false)
      .SetHasMember(true)
      .SetProperty(namePropertyInfo)
      .SetIsPrimaryKey(false)
      .Setup(mock => mock
        .Setup(x => x.Member)
        .Returns(namePropertyInfo))
      .Setup(mock => mock
        .Setup(x => x.GetValue)
        .Returns(namePropertyInfo.GetValue)))
      .Mocked();

    return EntityModelBuilder.Build(_ => _
      .SetType(entityType)
      .SetColumns(idProperty, nameProperty)
      .SetAutoGeneratedColumn(idProperty)
      .SetPrimaryKey(_ => _
        .SetIsComposite(false)
        .SetType(typeof(int))
        .SetColumns(idProperty))
      .SetNavigations()
      .SetInitializer(_ => _
        .SetConstructor(typeof(SimpleEntity).GetRequiredConstructor())
        .SetConstructorProperties()
        .SetInitializerProperties(idProperty, nameProperty)))
      .Mocked<SimpleEntity, int>();
  }

  public static IEntityModel<CompositeEntity, (Guid, int)> CreateCompositeEntityModel(bool autoGeneratedId)
  {
    EntityTypeDelegator entityType = new EntityTypeDelegator(typeof(CompositeEntity), autoGeneratedId);

    PropertyInfo id1PropertyInfo = typeof(CompositeEntity).GetRequiredProperty(nameof(CompositeEntity.Id1));
    PropertyInfo id2PropertyInfo = typeof(CompositeEntity).GetRequiredProperty(nameof(CompositeEntity.Id2));
    PropertyInfo namePropertyInfo = typeof(CompositeEntity).GetRequiredProperty(nameof(CompositeEntity.Name));

    IPrimaryKeyColumnModel id1Property = PrimaryKeyColumnModelBuilder.Build(_ => _
      .SetType(typeof(Guid))
      .SetIndex(0)
      .SetIsAutoGenerated(false)
      .SetHasMember(true)
      .SetProperty(id1PropertyInfo)
      .SetIsPrimaryKey(true)
      .Setup(mock => mock
        .Setup(x => x.Member)
        .Returns(id1PropertyInfo))
      .Setup(mock => mock
        .Setup(x => x.GetValue)
        .Returns(id1PropertyInfo.GetValue)))
      .Mocked();

    IPrimaryKeyColumnModel id2Property = PrimaryKeyColumnModelBuilder.Build(_ => _
      .SetType(typeof(int))
      .SetIndex(1)
      .SetIsAutoGenerated(autoGeneratedId)
      .SetHasMember(true)
      .SetProperty(id2PropertyInfo)
      .SetIsPrimaryKey(true)
      .Setup(mock => mock
        .Setup(x => x.Member)
        .Returns(id2PropertyInfo))
      .Setup(mock => mock
        .Setup(x => x.GetValue)
        .Returns(id2PropertyInfo.GetValue)))
      .Mocked();

    IOrdinaryColumnModel nameProperty = OrdinaryColumnModelBuilder.Build(_ => _
      .SetType(typeof(string))
      .SetIndex(2)
      .SetIsAutoGenerated(false)
      .SetHasMember(true)
      .SetProperty(namePropertyInfo)
      .SetIsPrimaryKey(false)
      .Setup(mock => mock
        .Setup(x => x.Member)
        .Returns(namePropertyInfo))
      .Setup(mock => mock
        .Setup(x => x.GetValue)
        .Returns(namePropertyInfo.GetValue)))
      .Mocked();

    return EntityModelBuilder.Build(_ => _
      .SetType(entityType)
      .SetColumns(id1Property, id2Property, nameProperty)
      .SetAutoGeneratedColumn(id2Property)
      .SetPrimaryKey(_ => _
        .SetIsComposite(true)
        .SetType(typeof((Guid, int)))
        .SetColumns(id1Property, id2Property)
        .SetTupleConstructor(typeof(Tuple<Guid, int>).GetRequiredConstructor(BindingFlags.Instance | BindingFlags.Public, new[] { typeof(Guid), typeof(int) })))
      .SetNavigations()
      .SetInitializer(_ => _
        .SetConstructor(typeof(CompositeEntity).GetRequiredConstructor())
        .SetConstructorProperties()
        .SetInitializerProperties(id1Property, id2Property, nameProperty)))
      .Mocked<CompositeEntity, (Guid, int)>();
  }

  private class EntityTypeDelegator : TypeDelegator
  {
    private readonly bool _autoGeneratedId;

    public EntityTypeDelegator(Type entityType, bool autoGeneratedId)
      : base(entityType)
    {
      _autoGeneratedId = autoGeneratedId;
    }

    public override string Name => _autoGeneratedId ? $"{base.Name}AutoGen" : base.Name;

    public override string? FullName => _autoGeneratedId ? $"{base.FullName}AutoGen" : base.FullName;
  }
}
