using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Model.FluentMock;
using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Fixtures.Models;

internal static class WithDifferentPrimaryKeys
{
  public class SimpleEntity
  {
    public int Id { get; set; }
    public string? Name { get; set; }
  }

  public class CompositeEntity
  {
    public Guid Id1 { get; set; }
    public int Id2 { get; set; }
    public string? Name { get; set; }
  }

  public static IEntityModel<SimpleEntity, int> CreateSimpleEntityModel(bool autoGeneratedId)
  {
    EntityTypeDelegator entityType = new EntityTypeDelegator(typeof(SimpleEntity), autoGeneratedId);

    PropertyInfo idPropertyInfo = typeof(SimpleEntity).GetRequiredProperty(nameof(SimpleEntity.Id));
    PropertyInfo namePropertyInfo = typeof(SimpleEntity).GetRequiredProperty(nameof(SimpleEntity.Name));

    IPrimaryKeyPropertyModel idProperty = PrimaryKeyPropertyModelBuilder.Build(_ => _
      .SetType(typeof(int))
      .SetIndex(0)
      .SetIsAutoGenerated(autoGeneratedId)
      .SetHasMember(true)
      .SetProperty(idPropertyInfo)
      .Setup(mock => mock
        .Setup(x => x.Member)
        .Returns(idPropertyInfo)));

    IOrdinaryPropertyModel nameProperty = OrdinaryPropertyModelBuilder.Build(_ => _
      .SetType(typeof(string))
      .SetIndex(1)
      .SetHasMember(true)
      .SetProperty(namePropertyInfo)
      .Setup(mock => mock
        .Setup(x => x.Member)
        .Returns(namePropertyInfo)));

    return EntityModelBuilder.Build(_ => _
      .SetType(entityType)
      .SetProperties(idProperty, nameProperty)
      .SetPrimaryKey(_ => _
        .SetIsComposite(false)
        .SetAutoGeneratedProperty(idProperty)
        .SetType(typeof(int))
        .SetProperties(idProperty))
      .SetNavigations()
      .SetInitializer(_ => _
        .SetConstructor(typeof(SimpleEntity).GetRequiredConstructor())
        .SetConstructorProperties()
        .SetInitializerProperties(idProperty, nameProperty)))
      .Mocked<SimpleEntity, int>();
  }

  public static IEntityModel<CompositeEntity, (Guid, int)> CreateCompositeEntityModel(bool autoGeneratedId)
  {
    EntityTypeDelegator entityType = new EntityTypeDelegator(typeof(CompositeEntity), autoGeneratedId);

    PropertyInfo id1PropertyInfo = typeof(CompositeEntity).GetRequiredProperty(nameof(CompositeEntity.Id1));
    PropertyInfo id2PropertyInfo = typeof(CompositeEntity).GetRequiredProperty(nameof(CompositeEntity.Id2));
    PropertyInfo namePropertyInfo = typeof(CompositeEntity).GetRequiredProperty(nameof(CompositeEntity.Name));

    IPrimaryKeyPropertyModel id1Property = PrimaryKeyPropertyModelBuilder.Build(_ => _
      .SetType(typeof(Guid))
      .SetIndex(0)
      .SetIsAutoGenerated(false)
      .SetHasMember(true)
      .SetProperty(id1PropertyInfo)
      .Setup(mock => mock
        .Setup(x => x.Member)
        .Returns(id1PropertyInfo)));

    IPrimaryKeyPropertyModel id2Property = PrimaryKeyPropertyModelBuilder.Build(_ => _
      .SetType(typeof(int))
      .SetIndex(1)
      .SetIsAutoGenerated(autoGeneratedId)
      .SetHasMember(true)
      .SetProperty(id2PropertyInfo)
      .Setup(mock => mock
        .Setup(x => x.Member)
        .Returns(id2PropertyInfo)));

    IOrdinaryPropertyModel nameProperty = OrdinaryPropertyModelBuilder.Build(_ => _
      .SetType(typeof(string))
      .SetIndex(2)
      .SetHasMember(true)
      .SetProperty(namePropertyInfo)
      .Setup(mock => mock
        .Setup(x => x.Member)
        .Returns(namePropertyInfo)));

    return EntityModelBuilder.Build(_ => _
      .SetType(entityType)
      .SetProperties(id1Property, id2Property, nameProperty)
      .SetPrimaryKey(_ => _
        .SetIsComposite(true)
        .SetAutoGeneratedProperty(id2Property)
        .SetType(typeof((Guid, int)))
        .SetProperties(id1Property, id2Property)
        .SetTupleConstructor(typeof(Tuple<Guid, int>).GetRequiredConstructor(BindingFlags.Instance | BindingFlags.Public, new[] { typeof(Guid), typeof(int) })))
      .SetNavigations()
      .SetInitializer(_ => _
        .SetConstructor(typeof(CompositeEntity).GetRequiredConstructor())
        .SetConstructorProperties()
        .SetInitializerProperties(id1Property, id2Property, nameProperty)))
      .Mocked<CompositeEntity, (Guid, int)>();
  }

  private class EntityTypeDelegator : TypeDelegator
  {
    private readonly bool _autoGeneratedId;

    public EntityTypeDelegator(Type entityType, bool autoGeneratedId)
      : base(entityType)
    {
      _autoGeneratedId = autoGeneratedId;
    }

    public override string Name => _autoGeneratedId ? $"{base.Name}AutoGen" : base.Name;

    public override string? FullName => _autoGeneratedId ? $"{base.FullName}AutoGen" : base.FullName;
  }
}
