// <auto-generated />
using System;
using CodeArchitects.Platform.Data.Fixtures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeArchitects.Platform.Data.Migrations.MariaDb
{
    [DbContext(typeof(MariaDbDbContext))]
    [Migration("20230427192840_MariaDb")]
    partial class MariaDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("CartItemProduct", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("CartItemIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("CartItemCartId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProductId", "CartItemIndex", "CartItemCartId");

                    b.HasIndex("CartItemIndex", "CartItemCartId");

                    b.ToTable("CartItemProduct");
                });

            modelBuilder.Entity("CategoryTypology", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TypologyId")
                        .HasColumnType("char(36)");

                    b.HasKey("CategoryId", "TypologyId");

                    b.HasIndex("TypologyId");

                    b.ToTable("CategoryTypology");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.CartItem", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<Guid>("CartId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ShippingAddressId")
                        .HasColumnType("char(36)");

                    b.HasKey("Index", "CartId");

                    b.HasIndex("CartId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.ConcurrencyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConcurrencyEntity");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.CustomerClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerClaim");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId")
                        .IsUnique();

                    b.ToTable("Person");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TypologyId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TypologyId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.SerialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SerialEntity");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.ShippingAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShippingAddress");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Typology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Typology");
                });

            modelBuilder.Entity("CartItemProduct", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.CartItem", null)
                        .WithMany()
                        .HasForeignKey("CartItemIndex", "CartItemCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryTypology", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Typology", null)
                        .WithMany()
                        .HasForeignKey("TypologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Address", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Customer", "Customer")
                        .WithOne("Address")
                        .HasForeignKey("CodeArchitects.Platform.Data.Fixtures.Model.Address", "CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Cart", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Customer", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.CartItem", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.ShippingAddress", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId");

                    b.Navigation("Cart");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.CustomerClaim", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Customer", null)
                        .WithMany("Claims")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Person", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Person", "Partner")
                        .WithOne()
                        .HasForeignKey("CodeArchitects.Platform.Data.Fixtures.Model.Person", "PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Product", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Typology", "Typology")
                        .WithMany()
                        .HasForeignKey("TypologyId");

                    b.Navigation("Category");

                    b.Navigation("Typology");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Customer", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Carts");

                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
