version: '3.4'

services:
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    ports:
      - 5379:6379

  microservicea:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80

  microservicea-dapr:
    command: ["./daprd",
      "-app-id", "microservicea",
      "-app-port", "80",
      "-components-path", "/components"
      ]
    volumes:
      - ./Dapr/components:/components

  microserviceb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:80

  microserviceb-dapr:
    command: ["./daprd",
      "-app-id", "microserviceb",
      "-app-port", "80",
      "-components-path", "/components"
      ]
    volumes:
      - ./Dapr/components:/components
