using CodeArchitects.Platform.Actors.Analyzer.Utils;
using Microsoft.CodeAnalysis;
using System.Text;

namespace CodeArchitects.Platform.Actors.Analyzer.Generator;

internal readonly ref struct DiagnosticReferenceRenderer
{
  private readonly SourceProductionContext _context;

  public DiagnosticReferenceRenderer(SourceProductionContext context)
  {
    _context = context;
  }

  public void Render(RecordList<DiagnosticReference> diagnostics)
  {
    StringBuilder source = new StringBuilder();

    source.AppendLine("// <auto-generated />");
    source.AppendLine();
    source.AppendLine("#if false");
    foreach (DiagnosticReference diagnostic in diagnostics)
    {
      diagnostic.ToString(source);
      source.AppendLine();
    }
    source.AppendLine("#endif");

    _context.AddSource("ActorDiagnostics.g.cs", source.ToString());
  }
}