// <auto-generated />
using System;
using CodeArchitects.Platform.Data.Fixtures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeArchitects.Platform.Data.Migrations.Postgres
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20221114155012_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("CA:Multitenancy:TenantIdType", typeof(Guid))
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryTypology", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypologiesId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "TypologiesId");

                    b.HasIndex("TypologiesId");

                    b.ToTable("CategoryTypology");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.CartItem", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Index", "CartId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId")
                        .IsUnique();

                    b.ToTable("Person");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("TypologyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TypologyId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.TenantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TenantEntity");

                    b.HasAnnotation("CA:Multitenancy:PropertyName", "TenantId");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Typology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Typology");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.UserClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim");
                });

            modelBuilder.Entity("CategoryTypology", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Typology", null)
                        .WithMany()
                        .HasForeignKey("TypologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Address", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.User", null)
                        .WithOne("Address")
                        .HasForeignKey("CodeArchitects.Platform.Data.Fixtures.Model.Address", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Cart", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.CartItem", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Person", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Person", "Partner")
                        .WithOne()
                        .HasForeignKey("CodeArchitects.Platform.Data.Fixtures.Model.Person", "PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Product", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.Typology", "Typology")
                        .WithMany()
                        .HasForeignKey("TypologyId");

                    b.Navigation("Category");

                    b.Navigation("Typology");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.UserClaim", b =>
                {
                    b.HasOne("CodeArchitects.Platform.Data.Fixtures.Model.User", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.Cart", b =>
                {
                    b.Navigation("Items")
                        .HasAnnotation("CA:AssociationKind", "<runtime annotation>");
                });

            modelBuilder.Entity("CodeArchitects.Platform.Data.Fixtures.Model.User", b =>
                {
                    b.Navigation("Address")
                        .HasAnnotation("CA:AssociationKind", "<runtime annotation>");

                    b.Navigation("Carts")
                        .HasAnnotation("CA:AssociationKind", "<runtime annotation>");

                    b.Navigation("Claims")
                        .HasAnnotation("CA:AssociationKind", "<runtime annotation>");
                });
#pragma warning restore 612, 618
        }
    }
}
