using CodeArchitects.Platform.Data.AdoNet.Executor;
using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Navigation;
using System.Data;

namespace CodeArchitects.Platform.Data.AdoNet.Command;

internal class CommandBuilder : ICommandBuilder
{
  private readonly ISqlTextBuilder _sqlBuilder;

  public CommandBuilder(ISqlTextBuilder sqlBuilder)
  {
    _sqlBuilder = sqlBuilder;
  }

  public void BuildSelectCommand<TEntity, TKey>(IDbCommand command, TKey key, in NavigationSpec<TEntity, TKey> spec)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    IEntityModel<TEntity, TKey> model = spec.Entity;

    command.CommandText = _sqlBuilder.BuildSelectText(spec);

    for (int i = 0; i < model.PrimaryKey.Columns.Count; i++)
    {
      CreateParameter(command, $"p{i}", model.PrimaryKey.GetKeyComponent(key, i));
    }
  }

  public void BuildInsertCommand(IDbCommand command, object node, IEntityModel model, in NavigationContext context)
  {
    command.Parameters.Clear();
    command.CommandText = _sqlBuilder.BuildInsertText(model);

    ParameterValueVisitor visitor = new(node);
    foreach (IColumnModel column in model.Columns)
    {
      if (column.IsAutoGenerated)
        continue;

      object? value = visitor.GetColumnValue(column, in context);
      CreateParameter(command, $"p{column.Index}", value);
    }
  }

  public void BuildUpdateCommand(IDbCommand command, object node, IEntityModel model, in NavigationContext context)
  {
    command.Parameters.Clear();
    command.CommandText = _sqlBuilder.BuildUpdateText(model);

    ParameterValueVisitor visitor = new(node);
    foreach (IColumnModel column in model.Columns)
    {
      object? value = visitor.GetColumnValue(column, in context);
      CreateParameter(command, $"p{column.Index}", value);
    }
  }

  public void BuildDeleteCommand(IDbCommand command, object node, IEntityModel model)
  {
    command.Parameters.Clear();
    command.CommandText = _sqlBuilder.BuildDeleteText(model);

    for (int i = 0; i < model.PrimaryKey.Columns.Count; i++)
    {
      CreateParameter(command, $"p{i}", model.PrimaryKey.Columns[i].GetValue(node));
    }
  }

  public void BuildDeleteCommand<TEntity, TKey>(IDbCommand command, TKey key, IEntityModel<TEntity, TKey> model)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    command.CommandText = _sqlBuilder.BuildDeleteText(model);

    for (int i = 0; i < model.PrimaryKey.Columns.Count; i++)
    {
      CreateParameter(command, $"p{i}", model.PrimaryKey.GetKeyComponent(key, i));
    }
  }

  private static void CreateParameter(IDbCommand command, string name, object? value)
  {
    IDbDataParameter parameter = command.CreateParameter();
    parameter.ParameterName = name;
    parameter.Value = value;
    command.Parameters.Add(parameter);
  }

  private readonly struct ParameterValueVisitor : IColumnModelVisitor<object?, NavigationContext>
  {
    private readonly object _node;

    public ParameterValueVisitor(object node)
    {
      _node = node;
    }

    public object? GetColumnValue(IColumnModel column, in NavigationContext context)
    {
      return column.Accept<ParameterValueVisitor, object?, NavigationContext>(in this, in context);
    }

    public object? VisitForeignKey(IForeignKeyColumnModel columnModel, in NavigationContext context)
    {
      return GetNavigatableValue(columnModel, in context);
    }

    public object? VisitJoin(IJoinColumnModel columnModel, in NavigationContext state)
    {
      return GetAccessibleValue(columnModel);
    }

    public object? VisitOrdinary(IOrdinaryColumnModel columnModel, in NavigationContext context)
    {
      return GetAccessibleValue(columnModel);
    }

    public object? VisitPrimaryAndForeignKey(IPrimaryAndForeignKeyColumnModel columnModel, in NavigationContext context)
    {
      return GetNavigatableValue(columnModel, in context);
    }

    public object? VisitPrimaryKey(IPrimaryKeyColumnModel columnModel, in NavigationContext context)
    {
      return GetAccessibleValue(columnModel);
    }


    private object? GetAccessibleValue(IAccessibleColumnModel columnModel)
    {
      return columnModel.GetValue(_node);
    }

    private object? GetNavigatableValue(IForeignKeyColumnModel columnModel, in NavigationContext context)
    {
      INavigationModel navigationModel = columnModel.Navigation;

      if (context != default && navigationModel.Inverse.Id == context.NavigationModel.Id)
      {
        object? value = columnModel.PrimaryKeyColumn.GetValue(context.Parent);
        if (navigationModel.HasMember)
        {
          navigationModel.SetValue(_node, context.Parent);
        }
        if (columnModel.HasMember)
        {
          columnModel.SetValue(_node, value);
        }

        return value;
      }

      if (navigationModel.HasMember && navigationModel.GetValue(_node) is { } navigation)
      {
        object? value = columnModel.PrimaryKeyColumn.GetValue(navigation);
        if (columnModel.HasMember)
        {
          columnModel.SetValue(_node, value);
        }

        return value;
      }

      if (columnModel.HasMember)
        return columnModel.GetValue(_node);

      return null;
    }
  }
}
