using CodeArchitects.Platform.Data.AdoNet.Features.Concurrency;
using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Navigation;
using CodeArchitects.Platform.Data.AdoNet.Visitors;
using System.Data;

namespace CodeArchitects.Platform.Data.AdoNet.Command;

internal class CommandBuilder<TDbCommand> : ICommandBuilder<TDbCommand>
  where TDbCommand : IDbCommand
{
  private readonly ISqlTextBuilder _sqlBuilder;
  private readonly IConcurrencyContext _concurrencyContext;

  public CommandBuilder(ISqlTextBuilder sqlBuilder, IConcurrencyContext concurrencyContext)
  {
    _sqlBuilder = sqlBuilder;
    _concurrencyContext = concurrencyContext;
  }

  public void BuildFindCommand<TEntity, TKey>(TDbCommand command, TKey key, INavigationRoot<TEntity, TKey> root)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    IEntityModel<TEntity, TKey> model = root.Entity;

    command.CommandText = _sqlBuilder.BuildFindText(root);

    for (int i = 0; i < model.PrimaryKey.Columns.Count; i++)
    {
      object? value = model.PrimaryKey.GetKeyComponent(key, i);
      CreateParameter(command, $"p{i}", value);
    }
  }

  public void BuildInsertCommand(TDbCommand command, object entity, IEntityModel model, NavigationContext context)
  {
    command.Parameters.Clear();
    command.CommandText = _sqlBuilder.BuildInsertText(model);

    ParameterValueVisitor visitor = new(context);
    foreach (IColumnModel column in model.Columns)
    {
      if (column.IsAutoGenerated)
        continue;

      object? value = visitor.GetColumnValue(column, entity);
      CreateParameter(command, $"p{column.Index}", value);
    }
  }

  public void BuildUpdateCommand(TDbCommand command, object entity, IEntityModel model, NavigationContext context)
  {
    command.Parameters.Clear();
    command.CommandText = _sqlBuilder.BuildUpdateText(model);

    ParameterValueVisitor visitor = new(context);
    foreach (IColumnModel column in model.Columns)
    {
      object? value = visitor.GetColumnValue(column, entity);
      CreateParameter(command, $"p{column.Index}", value);
    }

    if (model.UsesConcurrencyChecks)
    {
      object concurrencyToken = _concurrencyContext.GetToken(entity);
      CreateParameter(command, Constants.ConcurrencyTokenParameterName, concurrencyToken);
    }
  }

  public void BuildUpsertCommand(TDbCommand command, object entity, IEntityModel model)
  {
    command.Parameters.Clear();
    command.CommandText = _sqlBuilder.BuildUpsertText(model);

    foreach (IColumnModel column in model.Columns)
    {
      if (column.IsAutoGenerated || !column.HasMember)
        continue;

      object? value = column.GetValue(entity);
      CreateParameter(command, $"p{column.Index}", value);
    }
  }

  public void BuildRemoveCommand(TDbCommand command, object entity, IEntityModel model)
  {
    command.Parameters.Clear();
    command.CommandText = _sqlBuilder.BuildRemoveText(model);

    for (int i = 0; i < model.PrimaryKey.Columns.Count; i++)
    {
      object? value = model.PrimaryKey.Columns[i].GetValue(entity);
      CreateParameter(command, $"p{i}", value);
    }
  }

  public void BuildRemoveCommand<TEntity, TKey>(TDbCommand command, TKey key, IEntityModel<TEntity, TKey> model)
    where TEntity : class
    where TKey : IEquatable<TKey>
  {
    command.CommandText = _sqlBuilder.BuildRemoveText(model);

    for (int i = 0; i < model.PrimaryKey.Columns.Count; i++)
    {
      object? value = model.PrimaryKey.GetKeyComponent(key, i);
      CreateParameter(command, $"p{i}", value);
    }
  }

  public void BuildCountCommand(TDbCommand command, IEntityModel model)
  {
    command.CommandText = _sqlBuilder.BuildCountText(model);
  }

  public string BuildCustomCommand(string query, INavigationRoot root)
  {
    return _sqlBuilder.BuildCustomText(query, root);
  }

  public void BuildInsertManyCommand(TDbCommand command, IEnumerable<object> entities, IEntityModel model, NavigationContext context)
  {
    command.Parameters.Clear();

    int count = 0;
    ParameterValueVisitor visitor = new(context);
    foreach (object entity in entities)
    {
      int offset = count * model.Columns.Count;
      foreach (IColumnModel column in model.Columns)
      {
        if (column.IsAutoGenerated)
          continue;

        object? value = visitor.GetColumnValue(column, entity);
        CreateParameter(command, $"p{offset + column.Index}", value);
      }

      count++;
    }

    command.CommandText = _sqlBuilder.BuildInsertManyText(count, model);
  }

  protected virtual void CreateParameter(TDbCommand command, string name, object? value)
  {
    IDbDataParameter parameter = command.CreateParameter();
    parameter.ParameterName = name;
    parameter.Value = value ?? DBNull.Value;
    command.Parameters.Add(parameter);
  }

  private sealed class ParameterValueVisitor : IColumnModelVisitor<object?, object>
  {
    private readonly NavigationContext _context;

    public ParameterValueVisitor(NavigationContext context)
    {
      _context = context;
    }

    public object? GetColumnValue(IColumnModel column, object node)
    {
      return column.Accept(this, in node);
    }

    public object? VisitForeignKey(IForeignKeyColumnModel columnModel, in object node)
    {
      return GetNavigatableValue(columnModel, node);
    }

    public object? VisitOrdinary(IOrdinaryColumnModel columnModel, in object node)
    {
      return columnModel.GetValue(node);
    }

    public object? VisitPrimaryAndForeignKey(IPrimaryAndForeignKeyColumnModel columnModel, in object node)
    {
      return GetNavigatableValue(columnModel, node);
    }

    public object? VisitPrimaryKey(IPrimaryKeyColumnModel columnModel, in object node)
    {
      return columnModel.GetValue(node);
    }


    private object? GetNavigatableValue(IForeignKeyColumnModel columnModel, object node)
    {
      INavigationModel navigationModel = columnModel.Navigation;

      if (_context != default && navigationModel.Inverse.Id == _context.NavigationModel.Id)
      {
        if (_context.HasRemovedParent)
        {
          if (navigationModel.HasMember)
          {
            navigationModel.SetValue(node, null);
          }
          if (columnModel.HasMember)
          {
            columnModel.SetValue(node, columnModel.DefaultValue);
          }

          return null;
        }

        object parent = _context.Parent;
        object? value = columnModel.PrimaryKeyColumn.GetValue(parent);
        if (navigationModel.HasMember)
        {
          navigationModel.SetValue(node, parent);
        }
        if (columnModel.HasMember)
        {
          columnModel.SetValue(node, value);
        }

        return value;
      }

      if (navigationModel.HasMember && navigationModel.GetValue(node) is { } navigation)
      {
        object? value = columnModel.PrimaryKeyColumn.GetValue(navigation);
        if (columnModel.HasMember)
        {
          columnModel.SetValue(node, value);
        }

        return value;
      }

      if (columnModel.HasMember)
        return columnModel.GetValue(node);

      return null;
    }
  }
}
