using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Navigation;
using CodeArchitects.Platform.Data.Features.Associations;

namespace CodeArchitects.Platform.Data.AdoNet.Command;

internal class SqlTextBuilder : ISqlTextBuilder
{
  private readonly ISqlTextCache _cache;
  private readonly ISyntaxProvider _syntaxProvider;

  public SqlTextBuilder(ISqlTextCache cache, ISyntaxProvider syntaxProvider)
  {
    _cache = cache;
    _syntaxProvider = syntaxProvider;
  }

  public string BuildFindText(INavigationRoot root)
  {
    return _cache.GetOrAddFindText(root, this, static (root, self) =>
    {
      SqlStringBuilder stringBuilder = new(self._syntaxProvider);
      self.BuildFindText(in stringBuilder, root);
      return stringBuilder.ToString();
    });
  }

  public string BuildInsertText(IEntityModel entityModel)
  {
    return _cache.GetOrAddInsertText(entityModel, this, static (entityModel, self) =>
    {
      SqlStringBuilder stringBuilder = new(self._syntaxProvider);
      self.BuildInsertText(in stringBuilder, entityModel);
      return stringBuilder.ToString();
    });
  }

  public string BuildUpdateText(IEntityModel entityModel)
  {
    return _cache.GetOrAddUpdateText(entityModel, this, static (entityModel, self) =>
    {
      SqlStringBuilder stringBuilder = new(self._syntaxProvider);
      self.BuildUpdateText(in stringBuilder, entityModel);
      return stringBuilder.ToString();
    });
  }

  public string BuildUpsertText(IEntityModel entityModel)
  {
    return _cache.GetOrAddUpsertText(entityModel, this, static (entityModel, self) =>
    {
      SqlStringBuilder stringBuilder = new(self._syntaxProvider);
      self.BuildUpsertText(in stringBuilder, entityModel);
      return stringBuilder.ToString();
    });
  }

  public string BuildRemoveText(IEntityModel entityModel)
  {
    return _cache.GetOrAddRemoveText(entityModel, this, static (entityModel, self) =>
    {
      SqlStringBuilder stringBuilder = new(self._syntaxProvider);
      self.BuildRemoveText(in stringBuilder, entityModel);
      return stringBuilder.ToString();
    });
  }

  private void BuildFindText(in SqlStringBuilder stringBuilder, INavigationRoot root)
  {
    if (root.Navigations is { Count: > 0 } navigations)
    {
      BuildFindTextWithJoins(in stringBuilder, root.Entity, navigations);
    }
    else
    {
      BuildFindTextNoJoins(in stringBuilder, root.Entity);
    }

    static void BuildFindTextNoJoins(in SqlStringBuilder stringBuilder, IEntityModel entityModel)
    {
      stringBuilder.Append("SELECT ");
      stringBuilder.AppendJoin(", ", entityModel.Columns, AppendColumn);
      stringBuilder.AppendLine();
      stringBuilder.Append("FROM ");
      stringBuilder.AppendEscaped(entityModel.TableName);
      stringBuilder.AppendLine();
      stringBuilder.Append("WHERE ");
      stringBuilder.AppendWhereConditions(entityModel.PrimaryKey.Columns);

      static void AppendColumn(in SqlStringBuilder stringBuilder, IColumnModel columnModel)
      {
        stringBuilder.AppendEscaped(columnModel.Name);
      }
    }

    static void BuildFindTextWithJoins(in SqlStringBuilder stringBuilder, IEntityModel entityModel, IReadOnlyCollection<INavigation> navigations)
    {
      stringBuilder.Append("SELECT ");
      stringBuilder.AppendColumns(entityModel.Columns);
      stringBuilder.AppendChildrenColumns(navigations);
      stringBuilder.AppendLine();
      stringBuilder.AppendLine("FROM (");
      BuildFindTextNoJoins(in stringBuilder, entityModel);
      stringBuilder.AppendLine();
      stringBuilder.Append(')');
      stringBuilder.AppendTableAlias();

      foreach (INavigation child in navigations)
      {
        stringBuilder.AppendLine();
        stringBuilder.AppendLeftJoin(child);
      }
    }
  }

  private void BuildInsertText(in SqlStringBuilder stringBuilder, IEntityModel entityModel)
  {
    IEnumerable<IColumnModel> columns = entityModel.Columns.Where(column => !column.IsAutoGenerated);

    stringBuilder.Append("INSERT INTO ");
    stringBuilder.AppendEscaped(entityModel.TableName);
    stringBuilder.Append(" (");
    stringBuilder.AppendJoin(", ", columns, AppendColumns);
    stringBuilder.Append(')');
    stringBuilder.AppendOutputBefore(entityModel);
    stringBuilder.Append(" VALUES (");
    stringBuilder.AppendParameters(columns);
    stringBuilder.Append(')');
    stringBuilder.AppendOutputAfter(entityModel);

    static void AppendColumns(in SqlStringBuilder stringBuilder, IColumnModel columnModel)
    {
      stringBuilder.AppendEscaped(columnModel.Name);
    }
  }

  private void BuildUpdateText(in SqlStringBuilder stringBuilder, IEntityModel entityModel)
  {
    IEnumerable<IColumnModel> columns = entityModel.Columns.Where(column => column.IsForeignKey || !column.IsPrimaryKey);

    stringBuilder.Append("UPDATE ");
    stringBuilder.AppendEscaped(entityModel.TableName);
    stringBuilder.Append(" SET ");
    stringBuilder.AppendJoin(", ", columns, AppendColumnUpdate);
    stringBuilder.Append(" WHERE ");
    stringBuilder.AppendWhereConditions(entityModel.PrimaryKey.Columns);

    static void AppendColumnUpdate(in SqlStringBuilder stringBuilder, IColumnModel columnModel)
    {
      stringBuilder.AppendEscaped(columnModel.Name);
      stringBuilder.Append(" = ");

      if (columnModel is IForeignKeyColumnModel { HasMember: false, Navigation: { AssociationKind: AssociationKind.IntraAggregate, HasMember: false } })
      {
        stringBuilder.Append("COALESCE(");
        stringBuilder.AppendParameter(columnModel);
        stringBuilder.Append(", ");
        stringBuilder.AppendEscaped(columnModel.Name);
        stringBuilder.Append(")");
      }
      else
      {
        stringBuilder.AppendParameter(columnModel);
      }
    }
  }

  private void BuildUpsertText(in SqlStringBuilder stringBuilder, IEntityModel entityModel)
  {
    stringBuilder.Append("IF EXISTS (SELECT * FROM ");
    stringBuilder.AppendEscaped(entityModel.TableName);
    stringBuilder.Append(" WHERE ");
    stringBuilder.AppendWhereConditions(entityModel.PrimaryKey.Columns);
    stringBuilder.AppendLine(")");
    BuildUpdateText(in stringBuilder, entityModel);
    stringBuilder.AppendLine();
    stringBuilder.AppendLine("ELSE");
    BuildInsertText(stringBuilder, entityModel);
  }

  private void BuildRemoveText(in SqlStringBuilder stringBuilder, IEntityModel entityModel)
  {
    stringBuilder.Append("DELETE FROM ");
    stringBuilder.AppendEscaped(entityModel.TableName);
    stringBuilder.Append(" WHERE ");
    stringBuilder.AppendWhereConditions(entityModel.PrimaryKey.Columns);
  }
}
