using CodeArchitects.Platform.Data.AdoNet.Command.Select;
using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Navigation;
using System.Text;

namespace CodeArchitects.Platform.Data.AdoNet.Command;

internal class SqlTextBuilder : ISqlTextBuilder // TODO: Support multiple database providers
{
  private readonly ISqlTextCache _cache;

  public SqlTextBuilder(ISqlTextCache cache)
  {
    _cache = cache;
  }

  public string BuildSelectText(NavigationSpec spec)
  {
    if (_cache.TryGetSelectText(spec, out string? text))
      return text;

    SelectStringBuilder stringBuilder = new();

    stringBuilder.AppendSelectFrom(spec.Entity, spec.Navigations);

    foreach (INavigation child in spec.Navigations)
    {
      stringBuilder.AppendLeftJoin(child);
    }

    text = stringBuilder.ToString();
    _cache.AddSelectText(spec, text);

    return text;
  }

  public string BuildInsertText(IEntityModel entity)
  {
    // TODO: Try get from cache

    IEnumerable<IPropertyModel> properties = entity.Properties.Where(property =>
      !property.IsPrimaryKey ||
      property is not IPrimaryKeyPropertyModel { IsAutoGenerated: true });

    StringBuilder stringBuilder = new StringBuilder()
      .Append("INSERT INTO [")
      .Append(entity.TableName)
      .Append("] (")
      .AppendJoin(", ", properties, static (stringBuilder, property) => stringBuilder
        .Append('[')
        .Append(property.ColumnName)
        .Append(']'))
      .Append(") VALUES (")
      .AppendJoin(", ", properties, static (stringBuilder, property) => stringBuilder
        .Append("@p")
        .Append(property.Index))
      .Append(')');

    if (entity.PrimaryKey.AutoGeneratedProperty is not null)
    {
      stringBuilder.Append(" SELECT @@IDENTITY");
    }

    string text = stringBuilder.ToString();
    // TODO: Cache

    return text;
  }

  public string BuildUpdateText(IEntityModel entity)
  {
    // TODO: Try get from cache
    IEnumerable<IPropertyModel> properties = entity.Properties.Where(property => property.IsForeignKey || !property.IsPrimaryKey);

    string text = new StringBuilder()
      .Append("UPDATE [")
      .Append(entity.TableName)
      .Append("] SET ")
      .AppendJoin(", ", properties, AppendColumnUpdate)
      .Append(" WHERE ")
      .AppendJoin(" AND ", entity.PrimaryKey.Properties, static (stringBuilder, property) => stringBuilder
        .Append('[')
        .Append(property.ColumnName)
        .Append("] = @p")
        .Append(property.Index))
      .ToString();

    // TODO: Cache

    return text;

    static void AppendColumnUpdate(StringBuilder stringBuilder, IPropertyModel property)
    {
      stringBuilder
        .Append('[')
        .Append(property.ColumnName)
        .Append("] = ");
      
      if (property is IForeignKeyPropertyModel { HasMember: false, Navigation: { IsAggregation: true, HasMember: false } })
      {
        stringBuilder
          .Append("COALESCE(@p")
          .Append(property.Index)
          .Append(", [")
          .Append(property.ColumnName)
          .Append("])");
      }
      else
      {
        stringBuilder
          .Append("@p")
          .Append(property.Index);
      }
    }
  }

  public string BuildDeleteText(IEntityModel entity)
  {
    // TODO: Try get from cache

    string text = new StringBuilder()
      .Append("DELETE FROM [")
      .Append(entity.TableName)
      .Append("] WHERE ")
      .AppendJoin(" AND ", entity.PrimaryKey.Properties, static (stringBuilder, property) => stringBuilder
        .Append('[')
        .Append(property.ColumnName)
        .Append("] = @p")
        .Append(property.PrimaryKeyIndex))
      .ToString();

    // TODO: Cache

    return text;
  }
}
