using CodeArchitects.Platform.Data.AdoNet.Command.Select;
using CodeArchitects.Platform.Data.AdoNet.Model;
using CodeArchitects.Platform.Data.AdoNet.Navigation;
using System.Text;

namespace CodeArchitects.Platform.Data.AdoNet.Command;

internal class SqlTextBuilder : ISqlTextBuilder // TODO: Support multiple database providers
{
  private readonly ISqlTextCache _cache;

  public SqlTextBuilder(ISqlTextCache cache)
  {
    _cache = cache;
  }

  public string BuildSelectText(NavigationSpec spec)
  {
    if (_cache.TryGetSelectText(spec, out string? text))
      return text;

    SelectStringBuilder stringBuilder = new();

    stringBuilder.AppendSelectFrom(spec.Entity, spec.Navigations);

    foreach (INavigation child in spec.Navigations)
    {
      stringBuilder.AppendLeftJoin(child);
    }

    text = stringBuilder.ToString();
    _cache.AddSelectText(spec, text);

    return text;
  }

  public string BuildInsertText(IEntityModel entity)
  {
    // TODO: Try get from cache

    string text = BuildInsertText(new StringBuilder(), entity);

    // TODO: Cache

    return text;
  }

  public string BuildUpdateText(IEntityModel entity)
  {
    // TODO: Try get from cache

    string text = BuildUpdateText(new StringBuilder(), entity);

    // TODO: Cache

    return text;
  }

  public string BuildUpsertText(IEntityModel entity)
  {
    // TODO: Try get from cache

    StringBuilder stringBuilder = new();

    stringBuilder
      .Append("IF EXISTS (SELECT * FROM [")
      .Append(entity.TableName)
      .Append("] WHERE ")
      .AppendJoin(" AND ", entity.PrimaryKey.Columns, static (stringBuilder, column) => AppendWhereCondition(stringBuilder, column))
      .AppendLine(")");

    BuildUpdateText(stringBuilder, entity);

    stringBuilder.AppendLine();
    stringBuilder.AppendLine("ELSE");

    BuildInsertText(stringBuilder, entity);

    string text = stringBuilder.ToString();

    // TODO: Cache

    return text;

    static void AppendWhereCondition(StringBuilder stringBuilder, IPrimaryKeyColumnModel column)
    {
      stringBuilder.Append('[');
      stringBuilder.Append(column.Name);
      stringBuilder.Append("] = @p");
      stringBuilder.Append(column.PrimaryKeyIndex);
    }
  }

  public string BuildDeleteText(IEntityModel entity)
  {
    // TODO: Try get from cache

    string text = new StringBuilder()
      .Append("DELETE FROM [")
      .Append(entity.TableName)
      .Append("] WHERE ")
      .AppendJoin(" AND ", entity.PrimaryKey.Columns, static (stringBuilder, column) => stringBuilder
        .Append('[')
        .Append(column.Name)
        .Append("] = @p")
        .Append(column.PrimaryKeyIndex))
      .ToString();

    // TODO: Cache

    return text;
  }

  private string BuildInsertText(StringBuilder stringBuilder, IEntityModel entity)
  {
    IEnumerable<IColumnModel> columns = entity.Columns.Where(column => !column.IsAutoGenerated);

    stringBuilder
      .Append("INSERT INTO [")
      .Append(entity.TableName)
      .Append("] (")
      .AppendJoin(", ", columns, static (stringBuilder, column) => stringBuilder
        .Append('[')
        .Append(column.Name)
        .Append(']'))
      .Append(") VALUES (")
      .AppendJoin(", ", columns, static (stringBuilder, column) => stringBuilder
        .Append("@p")
        .Append(column.Index))
      .Append(')');

    if (entity.AutoGeneratedColumn is not null)
    {
      stringBuilder.Append(" SELECT @@IDENTITY");
    }

    return stringBuilder.ToString();
  }

  private string BuildUpdateText(StringBuilder stringBuilder, IEntityModel entity)
  {
    IEnumerable<IColumnModel> properties = entity.Columns.Where(column => column.IsForeignKey || !column.IsPrimaryKey);

    stringBuilder
      .Append("UPDATE [")
      .Append(entity.TableName)
      .Append("] SET ")
      .AppendJoin(", ", properties, static (stringBuilder, column) => AppendColumnUpdate(stringBuilder, column))
      .Append(" WHERE ")
      .AppendJoin(" AND ", entity.PrimaryKey.Columns, static (stringBuilder, column) => stringBuilder
        .Append('[')
        .Append(column.Name)
        .Append("] = @p")
        .Append(column.Index));

    return stringBuilder.ToString();

    static void AppendColumnUpdate(StringBuilder stringBuilder, IColumnModel column)
    {
      stringBuilder
        .Append('[')
        .Append(column.Name)
        .Append("] = ");

      if (column is IForeignKeyColumnModel { HasMember: false, Navigation: { AssociationKind: AssociationKind.Aggregation, HasMember: false } })
      {
        stringBuilder
          .Append("COALESCE(@p")
          .Append(column.Index)
          .Append(", [")
          .Append(column.Name)
          .Append("])");
      }
      else
      {
        stringBuilder
          .Append("@p")
          .Append(column.Index);
      }
    }
  }
}
