using CodeArchitects.Platform.Data.AdoNet.Model;
using System.Reflection;

namespace CodeArchitects.Platform.Data.AdoNet.Fixtures;

internal class MockPrimaryKeyPropertyModel : IPrimaryKeyColumnModel
{
  private readonly IPrimaryKeyColumnModel _mock;

  public MockPrimaryKeyPropertyModel(IPrimaryKeyColumnModel mock)
  {
    _mock = mock;
  }

  public short PrimaryKeyIndex => _mock.PrimaryKeyIndex;

  public bool IsAutoGenerated => _mock.IsAutoGenerated;

  public bool IsPrimaryKey => _mock.IsPrimaryKey;

  public bool IsForeignKey => _mock.IsForeignKey;

  public string Name => _mock.Name;

  public short Index => _mock.Index;

  public MemberInfo Member => _mock.Member;

  public Getter<object?> GetValue => _mock.GetValue;

  public Setter<object?> SetValue => _mock.SetValue;

  public Type Type => _mock.Type;

  public FieldInfo? Field => _mock.Field;

  public PropertyInfo? Property => _mock.Property;

  public bool HasMember => _mock.HasMember;

  public TResult Accept<TVisitor, TResult>(in TVisitor visitor)
    where TVisitor : IColumnModelVisitor<TResult>
  {
    return visitor.VisitPrimaryKey(this);
  }

  public TResult Accept<TVisitor, TResult, TState>(in TVisitor visitor, in TState state)
    where TVisitor : IColumnModelVisitor<TResult, TState>
  {
    return visitor.VisitPrimaryKey(this, in state);
  }
}
